/**
 * The frontend↔backend contract check, response half.
 *
 * `__fixtures__/responses.ts` is not written by hand: it is generated by
 * `backend/internal/handler/contract_test.go`, which drives the real Go router
 * over httptest and writes each body out as a TypeScript literal annotated with
 * the type from `schema.ts` that this app expects it to be. Most of the checking
 * therefore happens in the compiler — an annotated literal is "fresh", so
 * TypeScript applies excess property checking and a field the backend adds,
 * renames or retypes is a `bun run typecheck` error inside the generated file.
 *
 * What is left for runtime is everything the type system cannot see:
 *
 *   - Optional fields. `cursor?` is satisfied by absence, so a backend that
 *     stopped sending it would still compile. The envelope shape is asserted
 *     directly instead.
 *   - Enum completeness. A fixture only contains the statuses that happened to
 *     occur in it, so the generator emits the backend's whole set and it is
 *     compared here against `CAPTURE_STATUSES` and its friends.
 *   - Values, not shapes. `x-amz-tagging` being present with the right content
 *     is the difference between an upload and a 403, and no type expresses it.
 *   - The frontend's own parsing. A problem document is asserted by pushing it
 *     through `problemFromResponse`, the function the app actually uses.
 */

import { describe, expect, it } from 'vitest';

import {
  BACKEND_CAPTURE_CONTENT_TYPES,
  BACKEND_CAPTURE_STATUSES,
  BACKEND_PENDING_CAPTURE_STATUSES,
  BACKEND_SEARCH_MATCH_FIELDS,
  capturesPage,
  captureCreated,
  captureDownload,
  captureFailed,
  exportJob,
  health,
  matchResponse,
  noteCreated,
  noteDetail,
  notesPage,
  problemConflict,
  problemNotFound,
  problemSpendCapped,
  problemValidation,
  ready,
  readyDegraded,
  searchPage,
  settings,
  settingsStored,
  tagsPage,
  tokenSet,
  webauthnOptions,
  webauthnStatus,
} from './__fixtures__/responses.ts';
import { putPresigned } from './endpoints.ts';
import { CORRELATION_HEADER, SPEND_CAP_PROBLEM_TYPE, problemFromResponse } from './problem.ts';
import {
  CAPTURE_STATUSES,
  TERMINAL_CAPTURE_STATUSES,
  isTerminalStatus,
  type CaptureContentType,
  type ProblemWire,
  type SearchField,
} from './schema.ts';
import { tokenSetFromWire } from './tokens.ts';

/** Rebuilds the `Response` the client would have received. */
function asResponse(body: unknown, status: number, contentType: string): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'content-type': contentType,
      [CORRELATION_HEADER]: 'header-correlation-id',
    },
  });
}

/**
 * The union members, as values. Written out rather than derived, because
 * deriving them from `CAPTURE_STATUSES` would make the comparison below
 * compare a list to itself.
 */
const EXPECTED_CAPTURE_STATUSES = [
  'uploaded',
  'transcribing',
  'routing',
  'cleaning',
  'appending',
  'appended',
  'needs_target',
  'no_content',
  'failed',
  'spend_capped',
];

const EXPECTED_SEARCH_FIELDS: SearchField[] = ['title', 'alias', 'tag', 'body', 'transcript'];

const OFFERED_CONTENT_TYPES: CaptureContentType[] = [
  'audio/webm',
  'audio/mp4',
  'audio/ogg',
  'audio/wav',
];

describe('the paginated envelope', () => {
  // A previous agent briefly had the backend answer with a bare array and the
  // continuation token in an X-Next-Cursor header. Every list in this app
  // destructures `items`, so that shape renders nothing and throws nothing.
  it('is {items, cursor} on every collection, never a bare array', () => {
    for (const [name, page] of Object.entries({
      notesPage,
      tagsPage,
      searchPage,
      capturesPage,
    })) {
      expect(Array.isArray(page), `${name} is a bare array, not an envelope`).toBe(false);
      expect(Array.isArray(page.items), `${name}.items is not an array`).toBe(true);
      if ('cursor' in page) {
        expect(typeof (page as { cursor?: unknown }).cursor).toBe('string');
      }
    }
  });

  it('carries a cursor key only when there is more to read', () => {
    // Every fixture corpus fits in one page, so an emitted cursor here would
    // mean the backend hands out a token that continues nothing.
    expect(Object.hasOwn(notesPage, 'cursor')).toBe(false);
    expect(Object.hasOwn(capturesPage, 'cursor')).toBe(false);
  });
});

describe('the capture status enum', () => {
  it('holds exactly the members the backend can write', () => {
    expect([...CAPTURE_STATUSES]).toEqual(EXPECTED_CAPTURE_STATUSES);
    expect([...BACKEND_CAPTURE_STATUSES]).toEqual([...CAPTURE_STATUSES]);
  });

  // The progress card stops polling on a terminal status. A status the backend
  // is not moving on from and this app does not call terminal is a spinner that
  // never stops.
  it('agrees with the backend about which statuses the pipeline is still moving', () => {
    const stillMoving = CAPTURE_STATUSES.filter((status) => !isTerminalStatus(status));
    expect(stillMoving).toEqual([...BACKEND_PENDING_CAPTURE_STATUSES]);

    const terminal = CAPTURE_STATUSES.filter(
      (status) => !BACKEND_PENDING_CAPTURE_STATUSES.includes(status as never),
    );
    expect(terminal).toEqual([...TERMINAL_CAPTURE_STATUSES]);
  });

  it('covers every status that appears in a captured response', () => {
    const seen = [
      captureFailed.status,
      captureCreated.capture.status,
      ...capturesPage.items.map((capture) => capture.status),
      ...(noteDetail.captures ?? []).map((capture) => capture.status),
    ];
    for (const status of seen) {
      expect(CAPTURE_STATUSES, `the backend returned an unknown status ${status}`).toContain(
        status,
      );
    }
    // An unrouted capture must be in the tenant list. It was not, once — the
    // list walked the note index and a capture with no note fell out of it.
    expect(capturesPage.items.map((capture) => capture.status)).toContain('needs_target');
  });

  // `error` is what the progress card renders under a failed capture. A backend
  // that stopped sending it, or sent "" instead of null, changes what the user
  // is told.
  it('pairs a failed capture with the error text and nothing else with it', () => {
    expect(captureFailed.status).toBe('failed');
    expect(typeof captureFailed.error).toBe('string');
    expect(captureFailed.error).not.toBe('');

    const appended = capturesPage.items.find((capture) => capture.status === 'appended');
    expect(appended?.error).toBeNull();
  });
});

describe('CaptureCreated', () => {
  // Every entry in `headers` is inside the presigned signature. Dropping
  // x-amz-tagging does not produce an untagged object; it produces a 403 on
  // every upload the app will ever make.
  it('carries the upload headers the PUT cannot succeed without', () => {
    expect(captureCreated.upload.headers).toBeDefined();
    expect(captureCreated.upload.headers?.['x-amz-tagging']).toBe(
      'chintan-artifact=capture-audio',
    );
    expect(captureCreated.upload.headers?.['Content-Type']).toBe('audio/webm');
    expect(typeof captureCreated.upload.max_bytes).toBe('number');
    expect(captureCreated.upload.max_bytes).toBeGreaterThan(0);
  });

  it('is uploaded by putPresigned with those headers unmodified', async () => {
    let sent: Headers | undefined;
    await putPresigned(captureCreated.upload, 'audio-bytes', {
      fetchImpl: async (_input, init) => {
        sent = new Headers(init?.headers);
        return new Response(null, { status: 200 });
      },
    });
    expect(sent?.get('x-amz-tagging')).toBe('chintan-artifact=capture-audio');
  });

  it('stops at a rejection, instead of repeating a request that cannot change', async () => {
    /*
     * S3 answers an expired or malformed presigned URL with 403, and no number
     * of retries will make an expired signature valid — only a new URL will.
     * The code said exactly that and did the opposite: the `throw` meant to
     * stop the loop was caught by the `catch` two lines below it, recorded as
     * `lastError`, and the loop ran the full retry budget. In production that
     * turned one dead credential into five identical 403s, and the backoff
     * between them meant the user waited seconds for a failure that was
     * knowable at once.
     */
    let attempts = 0;
    await expect(
      putPresigned(captureCreated.upload, 'audio-bytes', {
        fetchImpl: async () => {
          attempts += 1;
          return new Response(null, { status: 403 });
        },
      }),
    ).rejects.toThrow(/403/);

    expect(attempts).toBe(1);
  });

  it('does keep retrying a failure that a retry can fix', async () => {
    // The distinction is the point: 5xx and a dropped connection are transient,
    // and giving up on the first one would lose recordings to a cellular blip.
    let attempts = 0;
    await putPresigned(captureCreated.upload, 'audio-bytes', {
      maxRetries: 3,
      fetchImpl: async () => {
        attempts += 1;
        return new Response(null, { status: attempts < 3 ? 503 : 200 });
      },
    });

    expect(attempts).toBe(3);
  });

  it('offers a peaks upload that is not tagged for audio retention', () => {
    // The waveform envelope is the client's own derived data. Expiring it with
    // the source audio would empty every old capture's player.
    expect(captureCreated.peaks_upload).toBeDefined();
    expect(captureCreated.peaks_upload?.headers?.['x-amz-tagging']).toBeUndefined();
  });

  it('only offers container types the backend accepts', () => {
    for (const contentType of OFFERED_CONTENT_TYPES) {
      expect(
        BACKEND_CAPTURE_CONTENT_TYPES,
        `the app offers ${contentType} and POST /v1/captures refuses it`,
      ).toContain(contentType);
    }
  });
});

describe('problem+json', () => {
  const problems: Record<string, { body: ProblemWire; status: number }> = {
    readyDegraded: { body: readyDegraded, status: 503 },
    problemNotFound: { body: problemNotFound, status: 404 },
    problemValidation: { body: problemValidation, status: 400 },
    problemConflict: { body: problemConflict, status: 409 },
    problemSpendCapped: { body: problemSpendCapped, status: 429 },
  };

  it('parses through the app’s own reader and keeps the correlation id', async () => {
    for (const [name, { body, status }] of Object.entries(problems)) {
      const error = await problemFromResponse(
        asResponse(body, status, 'application/problem+json'),
      );
      expect(error.status, name).toBe(status);
      // The body's id wins over the header's: they are the same id, and the
      // body is what a user can copy out of a screenshot.
      expect(error.correlationId, `${name} lost its correlation id`).toBe(body.correlation_id);
      expect(error.title, name).toBeTruthy();
      expect(error.detail, name).toBeTruthy();
    }
  });

  it('gives an optimistic-concurrency loser the version to reconcile against', async () => {
    const error = await problemFromResponse(
      asResponse(problemConflict, 409, 'application/problem+json'),
    );
    expect(error.isConflict).toBe(true);
    expect(typeof error.currentVersion).toBe('number');
  });

  // A spend cap is a budget decision, not a fault. Retrying it burns the user's
  // battery and changes nothing — and the two 429s this API produces share the
  // title "Too Many Requests", so only `type` separates them.
  it('classifies the spend cap by its type, and refuses to retry it', async () => {
    expect(
      problemSpendCapped.type,
      'the backend and SPEND_CAP_PROBLEM_TYPE disagree, so a capped capture would be retried',
    ).toBe(SPEND_CAP_PROBLEM_TYPE);

    const error = await problemFromResponse(
      asResponse(problemSpendCapped, 429, 'application/problem+json'),
    );
    expect(error.isSpendCapped).toBe(true);
    expect(error.isRetryable).toBe(false);
  });

  // The other 429. If this ever reported a spend cap, a flood of login attempts
  // would stop backing off.
  it('does not mistake a rate limit for a spend cap', async () => {
    const error = await problemFromResponse(
      asResponse(
        { type: 'about:blank', title: 'Too Many Requests', status: 429, detail: 'too many attempts' },
        429,
        'application/problem+json',
      ),
    );
    expect(error.isSpendCapped).toBe(false);
    expect(error.isRetryable).toBe(true);
  });
});

describe('the remaining shapes the app reads', () => {
  it('reads health and readiness', () => {
    expect(health.status).toBe('ok');
    expect(ready.status).toBe('ok');
    expect(Object.keys(ready.checks).length).toBeGreaterThan(0);
    for (const check of Object.values(ready.checks)) {
      expect(typeof check.ok).toBe('boolean');
    }
  });

  it('reads the settings that were stored, not the ones that were sent', () => {
    expect(settings.cleanup_mode).toBe('faithful');
    expect(settings.theme).toBe('ink');
    expect(settingsStored.cleanup_mode).toBe('polished');
    expect(settingsStored.theme).toBe('nocturne');
    expect(settingsStored.retention_days).toBe(30);
  });

  it('reads a note, its detail and its verbatim flag', () => {
    expect(noteCreated.version).toBeGreaterThan(0);
    expect(noteDetail.body).toBeTruthy();
    expect(notesPage.items.some((note) => note.verbatim === true)).toBe(true);
  });

  it('reads search hits whose matched_in fields it knows how to render', () => {
    for (const field of BACKEND_SEARCH_MATCH_FIELDS) {
      expect(
        EXPECTED_SEARCH_FIELDS,
        `search can report matched_in "${field}" and SearchField does not include it`,
      ).toContain(field);
    }
    for (const hit of searchPage.items) {
      for (const field of hit.matched_in ?? []) {
        expect(EXPECTED_SEARCH_FIELDS).toContain(field);
      }
      expect(hit.excerpt, 'a body match with no excerpt renders a hit with no context').toBeTruthy();
    }
  });

  it('reads tags with their counts', () => {
    expect(tagsPage.items.length).toBeGreaterThan(0);
    for (const tag of tagsPage.items) {
      expect(typeof tag.count).toBe('number');
    }
  });

  it('reads the match response, including the id the router picked', () => {
    expect(matchResponse.auto_selected).toBe(true);
    expect(matchResponse.auto_select_id).toBeTruthy();
    expect(matchResponse.candidates.length).toBeGreaterThan(0);
  });

  it('reads an export job and a download URL', () => {
    expect(exportJob.status).toBe('ready');
    expect(exportJob.url).toBeTruthy();
    expect(captureDownload.url).toBeTruthy();
    expect(captureDownload.expires_at).toBeTruthy();
  });

  it('reads the biometric shapes', () => {
    expect(typeof webauthnStatus.enrolled).toBe('boolean');
    expect(webauthnOptions.challenge_id).toBeTruthy();
    expect(typeof webauthnOptions.options).toBe('object');
  });

  // The token set is the one response whose snake_case names are allowed
  // outside schema.ts, and only inside this parser. If it stops parsing, a
  // biometric unlock signs the user out instead of in.
  it('parses the biometric token set the way the session does', () => {
    const parsed = tokenSetFromWire(tokenSet, 0, null);
    expect(parsed.idToken).toBe(tokenSet.id_token);
    expect(parsed.accessToken).toBe(tokenSet.access_token);
    expect(parsed.expiresAt).toBeGreaterThan(0);
  });
});
