/**
 * Wire types, hand-written from `docs/api/openapi.yaml`.
 *
 * Hand-written rather than generated on purpose. The document is 980 lines and
 * uses `oneOf` discriminated bodies and `allOf` composition that every
 * TypeScript generator renders into something less readable than this, and a
 * generated file still has to be committed and reviewed. This is the same
 * amount of reviewable text with none of the toolchain.
 *
 * Field names are the wire's snake_case. Nothing above `endpoints.ts` should
 * need to touch these directly; that module maps them into the shapes the UI
 * uses. Keep this file in step with the YAML — it is the contract.
 */

/* ---------------------------------------------------------------------------
   Errors — RFC 9457
   --------------------------------------------------------------------------- */

export interface ProblemWire {
  type: string;
  title: string;
  status: number;
  detail?: string;
  instance?: string;
  correlation_id?: string;
  /** Present on 409 so the client can reconcile an optimistic-concurrency loss. */
  current_version?: number;
  /**
   * Why a 409 was answered, when the version alone does not say. The one
   * value today is `append_in_progress`: a recording is being filed into the
   * note this moment, the same write will be accepted in a second or two, and
   * the response's `Retry-After` says how long to wait.
   */
  reason?: string;
}

/* ---------------------------------------------------------------------------
   Pagination — every collection is an envelope, never a bare array
   --------------------------------------------------------------------------- */

export interface Page<T> {
  items: T[];
  /** Absent or empty when the collection is exhausted. */
  cursor?: string;
}

export interface PageQuery {
  cursor?: string;
  /** 1–200, default 50. */
  limit?: number;
}

/* ---------------------------------------------------------------------------
   Health and settings
   --------------------------------------------------------------------------- */

export interface ReadinessWire {
  status: 'ok' | 'degraded';
  checks: Record<string, { ok?: boolean; latency_ms?: number }>;
}

export type CleanupMode = 'faithful' | 'polished';
export type ThemeSetting = 'ink' | 'nocturne' | 'system';

export interface SettingsWire {
  cleanup_mode: CleanupMode;
  retention_days: number;
  theme: ThemeSetting;
  /**
   * Transcription language for captures whose note sets none, or whose note
   * is not yet known (a capture without `note_id` is transcribed before it is
   * routed). `'auto'` lets Whisper detect; otherwise an ISO-639-1 code.
   * Defaults to `'en'`.
   */
  default_language?: string;
  /**
   * The instance-wide daily provider budget, read-only. Reported by the
   * server so the app can show the ceiling that is enforced; a value sent on
   * PUT is ignored. The per-tenant cap this used to be went with v3 step 3.
   */
  daily_spend_cap_micros?: number;
}

/* ---------------------------------------------------------------------------
   Notes
   --------------------------------------------------------------------------- */

export interface NoteWire {
  id: string;
  title: string;
  aliases?: string[];
  tags?: string[];
  snippet?: string;
  updated_at: string;
  created_at?: string;
  version: number;
  archived: boolean;
  purge_after?: string | null;
  /**
   * Cleanup is bypassed for this note. Writable through `NoteUpdateWire` and
   * returned on every read — the toggle has to render the state it is in.
   *
   * Present here because the contract fixtures proved the backend sends it. The
   * OpenAPI document listed it on `NoteUpdate` only.
   */
  verbatim?: boolean;
  /**
   * Transcription language for captures recorded into this note: `'auto'` or
   * an ISO-639-1 code. Absent when the note inherits `default_language`.
   */
  language?: string;
  /**
   * The lowercased, marker-stripped body the server searches (≤ 32 KB). Sent
   * only by `GET /v1/notes?include=search_text`, for an offline corpus that
   * wants to match what the server matches; absent everywhere else.
   */
  search_text?: string;
  /**
   * The worker regenerates the whole-note cleaned view after every change to
   * the body it makes or is told about (append, move, delete). Default false.
   * Optional here only so existing literals keep compiling; the backend
   * always sends it.
   */
  auto_clean?: boolean;
  /**
   * The mode an automatic or unspecified clean runs in. Absent means
   * `'structured'`. Distinct from `cleaned.mode`, the mode of the stored view.
   */
  cleaned_mode?: NoteCleanMode;
}

export type NoteCleanMode = 'polished' | 'structured';

/**
 * The whole-note cleaned view: one pass of the cleanup model over the entire
 * body, as Markdown. Read-only — derived from the body by the worker and
 * regenerated by `POST /v1/notes/{id}/clean` or `auto_clean`; edits belong in
 * `body`.
 */
export interface NoteCleanedWire {
  /** Empty only when the most recent run failed before any view existed. */
  body: string;
  /** The mode `body` was generated in (or of the failed attempt, with no body). */
  mode: NoteCleanMode;
  /** RFC 3339. When `body` was generated (or when the attempt failed, with no body). */
  generated_at: string;
  /** The body changed after `generated_at`; the next successful run clears it. */
  stale: boolean;
  /**
   * Present after a failed run. Fixed, displayable sentences; never provider
   * text. Beside a `body`, the previous view was kept.
   */
  error?: string;
}

/** `POST /v1/notes/{id}/clean` answers 202 with this; the worker does the rest. */
export type CleanQueuedWire = NoteCleanQueuedWire;
export type CleanRequestWire = NoteCleanRequestWire;

export interface NoteDetailWire extends NoteWire {
  body: string;
  captures?: CaptureWire[];
  /**
   * `null` until the note has been cleaned (or a clean has failed) once.
   * Optional here only so existing literals keep compiling; the backend
   * always sends it.
   */
  cleaned?: NoteCleanedWire | null;
}

/** Body of `POST /v1/notes/{id}/clean`; the whole body is optional. */
export interface NoteCleanRequestWire {
  /** Absent means the note's `cleaned_mode`, else `'structured'`. */
  mode?: NoteCleanMode;
}

/** The 202 of `POST /v1/notes/{id}/clean`. */
export interface NoteCleanQueuedWire {
  status: 'queued';
  /** The mode the worker will write. */
  mode: NoteCleanMode;
}

export interface NoteCreateWire {
  title: string;
  body?: string;
  aliases?: string[];
  tags?: string[];
}

export interface NoteUpdateWire {
  version: number;
  title?: string;
  body?: string;
  aliases?: string[];
  tags?: string[];
  verbatim?: boolean;
  /** `'auto'`, an ISO-639-1 code, or `''` to inherit the tenant default again. */
  language?: string;
  /** See `NoteWire.auto_clean`. */
  auto_clean?: boolean;
  /**
   * Preference for future runs; it does not regenerate the view. The view
   * itself (`cleaned.body`) is read-only and cannot be sent.
   */
  cleaned_mode?: NoteCleanMode;
}

export type NoteState = 'active' | 'archived';

/**
 * Batch purge. The only batch endpoint on this API, and it exists because a
 * purge cascades to every capture's audio, transcripts, segments and peaks —
 * a hundred of those driven one at a time from a phone is a hundred round trips
 * that all have to survive the connection.
 *
 * Explicit ids only. "Clear all" is this client listing its archive and sending
 * the ids in batches; there is no server-side "delete everything" flag, on
 * purpose.
 */
export interface NotePurgeRequestWire {
  /** At most 100 per request. */
  note_ids: string[];
}

/**
 * One note's outcome.
 *
 * `purged` — gone, along with everything it owned.
 * `not_found` — no such note. Also what a replayed batch reports, which is what
 * makes a retry safe.
 * `failed` — still here. Either it was not archived (an active note is refused,
 * so a stale listing cannot turn "clear my archive" into "delete my notes"), or
 * part of its cascade failed and the row was kept so it can be retried.
 */
export type NotePurgeStatus = 'purged' | 'not_found' | 'failed';

export interface NotePurgeResultWire {
  note_id: string;
  status: NotePurgeStatus;
  /** Safe to display. Never contains provider or AWS internals. */
  detail?: string;
}

/**
 * The response is 200 even when some notes failed: no transaction spans
 * DynamoDB and S3, so one verdict for the batch would be a claim the server
 * cannot make. Render what survived.
 */
export interface NotePurgeResponseWire {
  results: NotePurgeResultWire[];
}

export interface NoteListQuery extends PageQuery {
  state?: NoteState;
  tag?: string;
  /**
   * `search_text` adds each row's searchable body. Opt-in because the list is
   * fetched constantly and renders none of it; the offline corpus asks once.
   */
  include?: 'search_text';
}

export interface TagWire {
  name: string;
  count: number;
}

/* ---------------------------------------------------------------------------
   Captures
   --------------------------------------------------------------------------- */

export const CAPTURE_STATUSES = [
  'uploaded',
  'transcribing',
  'routing',
  'cleaning',
  'appending',
  'appended',
  'needs_target',
  'no_content',
  'failed',
  'spend_capped',
] as const;

export type CaptureStatus = (typeof CAPTURE_STATUSES)[number];

/** Statuses the pipeline will not move on from without user action. */
export const TERMINAL_CAPTURE_STATUSES: readonly CaptureStatus[] = [
  'appended',
  'needs_target',
  'no_content',
  'failed',
  'spend_capped',
];

export function isTerminalStatus(status: CaptureStatus): boolean {
  return TERMINAL_CAPTURE_STATUSES.includes(status);
}

export interface CaptureWire {
  id: string;
  note_id?: string | null;
  status: CaptureStatus;
  error?: string | null;
  created_at: string;
  /**
   * Where the router thinks this recording belongs. Exactly one of the two is
   * ever set, and only on a `needs_target` capture: `suggested_note_id` names an
   * existing note it was confident enough to propose but not to append to
   * unasked, `suggested_title` is the title it would give a new note when there
   * was no plausible destination.
   *
   * The backend has always computed these — it pays an LLM call for them — and
   * used to drop them before the response left the API, which is why the
   * "where should this go?" prompt could only show an unranked list of every
   * note. They are declared here so the fixtures typecheck; rendering them is
   * the capture screen's to do.
   */
  suggested_note_id?: string | null;
  suggested_title?: string | null;
  appended_at?: string | null;
  duration_ms?: number | null;
  has_segments?: boolean;
  has_peaks?: boolean;
  /** True when a person chose the note (`note_id` at create, or `/target`); false when the router decided. Optional only until every backend sends it. */
  targeted?: boolean;
  version: number;
}

export type CaptureContentType = 'audio/webm' | 'audio/mp4' | 'audio/ogg' | 'audio/wav';

export interface CaptureCreateWire {
  content_type: CaptureContentType;
  note_id?: string | null;
  duration_ms?: number;
  size_bytes?: number;
}

export interface PresignedUploadWire {
  url: string;
  expires_at: string;
  max_bytes?: number;
  headers?: Record<string, string>;
}

export interface CaptureCreatedWire {
  capture: CaptureWire;
  upload: PresignedUploadWire & { max_bytes: number };
  /** Absent when the instance does not accept client-computed peaks. */
  peaks_upload?: PresignedUploadWire;
}

export type CaptureTargetWire = { note_id: string } | { new_note_title: string };

export type CaptureListStatus = 'pending' | 'failed' | 'needs_target' | 'all';

export interface CaptureListQuery extends PageQuery {
  status?: CaptureListStatus;
}

export type CaptureArtifactKind = 'audio' | 'raw' | 'clean' | 'segments' | 'peaks';

export interface PresignedDownloadWire {
  url: string;
  expires_at: string;
}

/** POST /v1/captures/{captureId}/move. 200 with the re-pointed capture, 204 when already there. */
export interface CaptureMoveWire {
  note_id: string;
}

/**
 * One entry of GET /v1/notes/{noteId}/recordings/urls: a presigned GET for a
 * recording's audio and the filename to save it under,
 * `<note-title-slug>-<yyyymmdd-hhmm>.<ext>`. The client zips these itself.
 */
export interface RecordingUrlWire {
  capture_id: string;
  filename: string;
  url: string;
  expires_at: string;
}

/** Every recording of a note that still has its audio, oldest first, at most 200. */
export interface RecordingUrlsWire {
  items: RecordingUrlWire[];
}

/* ---------------------------------------------------------------------------
   Match and search
   --------------------------------------------------------------------------- */

export interface MatchCandidateWire {
  note_id: string;
  title: string;
  score: number;
  reason?: string;
}

export interface MatchResponseWire {
  confidence: number;
  auto_selected?: boolean;
  candidates: MatchCandidateWire[];
  /**
   * The note the router picked when it was confident enough to pick one, which
   * is the same fact `auto_selected` reports as a boolean.
   *
   * The backend has always sent it and neither the OpenAPI document nor this
   * file declared it; the contract fixtures are what surfaced that.
   */
  auto_select_id?: string | null;
}

export type SearchField = 'title' | 'alias' | 'tag' | 'body' | 'transcript';

export interface SearchHitWire {
  note_id: string;
  title: string;
  excerpt?: string;
  matched_in?: SearchField[];
}

/* ---------------------------------------------------------------------------
   Ask — a question answered from the notes
   --------------------------------------------------------------------------- */

export type AskStatus = 'pending' | 'answered' | 'failed';

/** One earlier exchange of the same conversation, sent back as context. */
export interface AskTurnWire {
  question: string;
  answer: string;
}

/**
 * `POST /v1/ask`. The question is 1–1000 characters after trimming; `history`
 * is at most the six most recent earlier turns of THIS conversation, oldest
 * first, so a follow-up ("and when was that?") reads in context. Retrieval is
 * over the notes only, never over the history.
 */
export interface AskRequestWire {
  question: string;
  history?: AskTurnWire[];
}

/** A note the model was given and cited, in relevance order. */
export interface AskSourceWire {
  note_id: string;
  title: string;
}

/**
 * `GET /v1/ask/{askId}`. The API answers `POST /v1/ask` with 202 and this row
 * in `pending`; the worker fills in the rest and the client polls. `answer` is
 * plain text with at most the light Markdown the cleaned view uses —
 * paragraphs, `- ` lists, `**bold**` — and never headings. `grounded` is false
 * when the honest answer is "that is not in your notes". `error` is a fixed
 * user-facing sentence, never provider text. Rows live for a day.
 */
export interface AskWire {
  id: string;
  status: AskStatus;
  question: string;
  answer: string | null;
  grounded: boolean;
  sources: AskSourceWire[];
  error: string | null;
  /** How many notes were in the retrieval window. */
  notes_considered: number;
  created_at: string;
  answered_at: string | null;
}

/* ---------------------------------------------------------------------------
   Usage
   --------------------------------------------------------------------------- */

/** Provider spend counters. Microdollars, the unit the spend cap uses. */
export interface UsageTotalsWire {
  cost_micros: number;
  calls: number;
  audio_seconds?: number;
  input_tokens?: number;
  output_tokens?: number;
}

/**
 * The instance's AWS spend for the month, as last read from the stack's AWS
 * Budget by the worker's daily task. Instance-level — the account's bill, not
 * the caller's share of it — so every user sees the same figure. `share_micros`
 * is the one per-user number: the instance figure scaled by this user's share
 * of the instance's provider spend this month. Null when the instance has
 * spent nothing on providers yet, so there is nothing to apportion by.
 */
export interface UsageAwsWire {
  /** Month-to-date actual spend, microdollars. */
  month_micros: number;
  /** When the budget was read, RFC 3339. */
  as_of: string;
  /** The budget's limit, microdollars; null when the budget has none. */
  budget_micros: number | null;
  /**
   * Optional rather than nullable-required because the frontend may deploy
   * before the backend that sends it; the section falls back to the instance
   * figure when it is absent.
   */
  share_micros?: number | null;
  /** How the share was apportioned — `provider_cost` today; null with `share_micros`. */
  share_basis?: string | null;
}

/** Authenticated API requests this month by this user. Health and 401s excluded. */
export interface UsageApiWire {
  requests: number;
}

/**
 * What the tenant is keeping, counted from its index rows at read time.
 * `approximate` is true when the count stopped at the row cap, so the figures
 * are a floor rather than a total.
 */
export interface UsageStorageWire {
  recordings: number;
  audio_seconds: number;
  audio_bytes: number;
  notes: number;
  approximate: boolean;
  /**
   * The month's storage so far, from the worker's daily snapshot: the audio
   * bytes held each day, summed, and likewise the notes. Unlike the fields
   * above these do not read zero the moment everything is deleted. Optional
   * here because the screen may meet a backend from before the snapshot.
   */
  byte_days?: number;
  note_days?: number;
}

/**
 * `GET /v1/usage?month=yyyy-mm`: the caller's own provider usage for one
 * month — totals, the same split by pipeline stage and by provider, one line
 * per day, how many API requests the month took, and what is stored. A month
 * with no usage is all zeros, not an error. `aws` is null when nothing has
 * been recorded for the month (no budget in the stack, or the daily task has
 * not run yet).
 *
 * `providers`, `api` and `storage` are required by contract but optional here:
 * the screen has to render against a backend from before they existed, and
 * each has a graceful absence (no line, rather than "0").
 */
export interface UsageWire extends UsageTotalsWire {
  month: string;
  ops: Record<string, UsageTotalsWire>;
  days: Array<
    UsageTotalsWire & { date: string; api_requests?: number; storage_byte_days?: number }
  >;
  aws?: UsageAwsWire | null;
  /** The same totals split by provider name (`groq`, `minimax`…); absent providers omitted. */
  providers?: Record<string, UsageTotalsWire>;
  api?: UsageApiWire;
  storage?: UsageStorageWire;
}

/* ---------------------------------------------------------------------------
   Export and auth
   --------------------------------------------------------------------------- */

export interface ExportJobWire {
  id: string;
  status: 'pending' | 'running' | 'ready' | 'failed';
  url?: string | null;
  expires_at?: string | null;
  bytes?: number | null;
}

/**
 * The Cognito token set as it arrives on the wire. The ONLY place these
 * snake_case names are allowed to appear outside this file is
 * `tokens.tokenSetFromWire`, which parses them into the internal shape.
 */
export interface TokenSetWire {
  id_token: string;
  access_token: string;
  refresh_token?: string;
  expires_in: number;
  token_type: string;
}

/** Aliases used by the note screen; the canonical names are the backend's. */
export type CleanedWire = NoteCleanedWire;
export type CleanedMode = NoteCleanMode;
