package service

import (
	"context"
	"errors"
	"strings"
	"testing"

	"github.com/vppillai/chintan/backend/internal/model"
	"github.com/vppillai/chintan/backend/internal/repository/memory"
)

// withCleanedView gives a note a cleaned view as the worker would have left
// it, so a body write has something to mark stale.
func (h *editHarness) withCleanedView(userID string, n model.NoteIndex, autoClean bool, mode model.NoteCleanMode) model.NoteIndex {
	h.t.Helper()
	stored, err := h.store.GetNote(h.ctx, userID, n.ID)
	if err != nil {
		h.t.Fatalf("GetNote: %v", err)
	}
	stored.CleanedBody = "# Cleaned\n\nThe view."
	stored.CleanedMode = model.NoteCleanStructured
	stored.CleanedAt = model.Now()
	stored.CleanedStale = false
	stored.AutoClean = autoClean
	stored.CleanMode = mode
	updated, err := h.store.PutNote(h.ctx, userID, stored)
	if err != nil {
		h.t.Fatalf("PutNote: %v", err)
	}
	return updated
}

func (h *editHarness) get(userID, noteID string) model.NoteIndex {
	h.t.Helper()
	n, err := h.store.GetNote(h.ctx, userID, noteID)
	if err != nil {
		h.t.Fatalf("GetNote: %v", err)
	}
	return n
}

// Every body write marks an existing view stale; nothing else does.
func TestEditingTheBodyMarksTheCleanedViewStale(t *testing.T) {
	h := newEditHarness(t)
	n := h.withCleanedView("u", h.note("u", "Roof", "the gutter leaks"), false, "")

	version := n.Version
	title := "Roof repair"
	updated, err := h.notes.UpdateNote(h.ctx, "u", n.ID, NoteUpdates{Title: &title, ExpectedVersion: &version})
	if err != nil {
		t.Fatalf("UpdateNote(title): %v", err)
	}
	if updated.CleanedStale {
		t.Error("a title edit marked the view stale; only the body feeds the view")
	}
	if updated.CleanedBody == "" {
		t.Error("a title edit lost the cleaned body")
	}

	version = updated.Version
	body := "the gutter leaks badly"
	updated, err = h.notes.UpdateNote(h.ctx, "u", n.ID, NoteUpdates{Body: &body, ExpectedVersion: &version})
	if err != nil {
		t.Fatalf("UpdateNote(body): %v", err)
	}
	if !updated.CleanedStale {
		t.Error("a body edit did not mark the view stale")
	}
	if updated.CleanedBody != "# Cleaned\n\nThe view." {
		t.Errorf("a body edit changed the cleaned body itself: %q; the view is read-only and regenerated by the worker", updated.CleanedBody)
	}
}

func TestANoteWithoutAViewIsNeverStale(t *testing.T) {
	h := newEditHarness(t)
	n := h.note("u", "Roof", "the gutter leaks")
	version := n.Version
	body := "edited"
	updated, err := h.notes.UpdateNote(h.ctx, "u", n.ID, NoteUpdates{Body: &body, ExpectedVersion: &version})
	if err != nil {
		t.Fatalf("UpdateNote: %v", err)
	}
	if updated.CleanedStale {
		t.Error("a note that has never been cleaned was marked stale")
	}
}

func TestUpdateNoteStoresTheCleanPreferencesAndRefusesAnUnknownMode(t *testing.T) {
	h := newEditHarness(t)
	n := h.note("u", "Roof", "the gutter leaks")

	version := n.Version
	on, mode := true, model.NoteCleanPolished
	updated, err := h.notes.UpdateNote(h.ctx, "u", n.ID, NoteUpdates{AutoClean: &on, CleanMode: &mode, ExpectedVersion: &version})
	if err != nil {
		t.Fatalf("UpdateNote: %v", err)
	}
	if !updated.AutoClean || updated.CleanMode != model.NoteCleanPolished {
		t.Errorf("preferences not stored: auto_clean=%v mode=%q", updated.AutoClean, updated.CleanMode)
	}
	if updated.CleanedStale {
		t.Error("changing the preferences marked a non-existent view stale")
	}

	version = updated.Version
	bad := model.NoteCleanMode("faithful")
	if _, err := h.notes.UpdateNote(h.ctx, "u", n.ID, NoteUpdates{CleanMode: &bad, ExpectedVersion: &version}); !errors.Is(err, ErrInvalidNoteCleanMode) {
		t.Errorf("UpdateNote(cleaned_mode=faithful) = %v, want ErrInvalidNoteCleanMode", err)
	}
}

// Deleting a recording rewrites the body, so the view goes stale and, when the
// note asks, the worker is invoked — with the note's own mode, and only after
// the row is gone.
func TestDeletingARecordingMarksStaleAndAutoCleans(t *testing.T) {
	h := newEditHarness(t)
	worker := &stubInvoker{}
	h.captures.WithInvoker(worker)

	body := CaptureMarker("c_1") + "\nFirst take.\n\n" + CaptureMarker("c_2") + "\nSecond take."
	n := h.withCleanedView("u", h.note("u", "Roof", body), true, model.NoteCleanPolished)
	h.appended("u", n.ID, "c_1", "2026-01-01T09:00:00.000000000Z")
	h.appended("u", n.ID, "c_2", "2026-01-01T10:00:00.000000000Z")

	if err := h.captures.DeleteCapture(h.ctx, "u", "c_1"); err != nil {
		t.Fatalf("DeleteCapture: %v", err)
	}
	after := h.get("u", n.ID)
	if !after.CleanedStale {
		t.Error("deleting a recording did not mark the view stale")
	}
	if got := worker.calls; len(got) != 1 || got[0] != "clean-note/u/"+n.ID+"/polished" {
		t.Errorf("worker calls = %v, want one clean-note hand-off in the note's mode", got)
	}
}

func TestDeletingARecordingDoesNotAutoCleanANoteThatDidNotAsk(t *testing.T) {
	h := newEditHarness(t)
	worker := &stubInvoker{}
	h.captures.WithInvoker(worker)

	n := h.withCleanedView("u", h.note("u", "Roof", CaptureMarker("c_1")+"\nFirst take."), false, "")
	h.appended("u", n.ID, "c_1", "2026-01-01T09:00:00.000000000Z")
	if err := h.captures.DeleteCapture(h.ctx, "u", "c_1"); err != nil {
		t.Fatalf("DeleteCapture: %v", err)
	}
	if !h.get("u", n.ID).CleanedStale {
		t.Error("the view was not marked stale")
	}
	if len(worker.calls) != 0 {
		t.Errorf("worker was invoked %v for a note without auto_clean", worker.calls)
	}
}

// A move changes two bodies. Both views go stale, and each note that asked for
// it is regenerated — D2 said "structured mode re-runs on both notes".
func TestMovingARecordingMarksBothNotesStaleAndAutoCleansEach(t *testing.T) {
	h := newEditHarness(t)
	worker := &stubInvoker{}
	h.captures.WithInvoker(worker)

	source := h.withCleanedView("u", h.note("u", "Wrong", CaptureMarker("c_1")+"\nMisfiled."), true, model.NoteCleanStructured)
	target := h.withCleanedView("u", h.note("u", "Right", CaptureMarker("c_0")+"\nOriginal."), false, "")
	h.appended("u", source.ID, "c_1", "2026-01-01T09:00:00.000000000Z")
	h.appended("u", target.ID, "c_0", "2026-01-01T08:00:00.000000000Z")

	if _, moved, err := h.captures.MoveCapture(h.ctx, "u", "c_1", target.ID); err != nil || !moved {
		t.Fatalf("MoveCapture: moved=%v err=%v", moved, err)
	}
	if !h.get("u", source.ID).CleanedStale {
		t.Error("the source view was not marked stale")
	}
	if !h.get("u", target.ID).CleanedStale {
		t.Error("the target view was not marked stale")
	}
	if got := worker.calls; len(got) != 1 || got[0] != "clean-note/u/"+source.ID+"/structured" {
		t.Errorf("worker calls = %v, want exactly the source (the note that asked)", got)
	}
}

// The request path checks the note and invokes; it never runs the model.
func TestRequestCleanChecksTheNoteAndInvokesTheWorker(t *testing.T) {
	h := newEditHarness(t)
	worker := &stubInvoker{}
	h.notes.WithInvoker(worker)
	n := h.note("u", "Roof", "the gutter leaks")

	mode, err := h.notes.RequestClean(h.ctx, "u", n.ID, "")
	if err != nil {
		t.Fatalf("RequestClean: %v", err)
	}
	if mode != model.NoteCleanStructured {
		t.Errorf("default mode = %q, want structured", mode)
	}
	if _, err := h.notes.RequestClean(h.ctx, "u", n.ID, model.NoteCleanPolished); err != nil {
		t.Fatalf("RequestClean(polished): %v", err)
	}
	if got := strings.Join(worker.calls, ","); got != "clean-note/u/"+n.ID+"/structured,clean-note/u/"+n.ID+"/polished" {
		t.Errorf("worker calls = %v", worker.calls)
	}

	// The note's own preference is the default once set.
	stored := h.get("u", n.ID)
	stored.CleanMode = model.NoteCleanPolished
	if _, err := h.store.PutNote(h.ctx, "u", stored); err != nil {
		t.Fatalf("PutNote: %v", err)
	}
	if mode, err := h.notes.RequestClean(h.ctx, "u", n.ID, ""); err != nil || mode != model.NoteCleanPolished {
		t.Errorf("RequestClean with a stored preference = %q, %v; want polished", mode, err)
	}

	if _, err := h.notes.RequestClean(h.ctx, "u", n.ID, model.NoteCleanMode("faithful")); !errors.Is(err, ErrInvalidNoteCleanMode) {
		t.Errorf("RequestClean(faithful) = %v, want ErrInvalidNoteCleanMode", err)
	}
	if _, err := h.notes.RequestClean(h.ctx, "u", "missing", ""); err == nil {
		t.Error("RequestClean on a missing note succeeded")
	}

	if _, err := h.notes.ArchiveNote(h.ctx, "u", n.ID); err != nil {
		t.Fatalf("ArchiveNote: %v", err)
	}
	if _, err := h.notes.RequestClean(h.ctx, "u", n.ID, ""); !errors.Is(err, ErrNoteArchived) {
		t.Errorf("RequestClean on an archived note = %v, want ErrNoteArchived", err)
	}
}

func TestRequestCleanWithoutAWorkerSaysSo(t *testing.T) {
	store, objects := memory.NewStore(), memory.NewObjects()
	notes := NewNotesService(store, objects)
	n, err := notes.CreateNote(context.Background(), "u", "Roof", nil)
	if err != nil {
		t.Fatalf("CreateNote: %v", err)
	}
	if _, err := notes.RequestClean(context.Background(), "u", n.ID, ""); !errors.Is(err, ErrCaptureWorkerUnavailable) {
		t.Errorf("RequestClean without a worker = %v, want ErrCaptureWorkerUnavailable", err)
	}
}
