package service

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/vppillai/chintan/backend/internal/model"
	"github.com/vppillai/chintan/backend/internal/repository/memory"
)

// withCleanedView gives a note a cleaned view as the worker would have left
// it, so a body write has something to mark stale.
func (h *editHarness) withCleanedView(userID string, n model.NoteIndex, autoClean bool, mode model.NoteCleanMode) model.NoteIndex {
	h.t.Helper()
	stored, err := h.store.GetNote(h.ctx, userID, n.ID)
	if err != nil {
		h.t.Fatalf("GetNote: %v", err)
	}
	stored.CleanedBody = "# Cleaned\n\nThe view."
	stored.CleanedMode = model.NoteCleanStructured
	stored.CleanedAt = model.Now()
	stored.CleanedStale = false
	stored.AutoClean = autoClean
	stored.CleanMode = mode
	updated, err := h.store.PutNote(h.ctx, userID, stored)
	if err != nil {
		h.t.Fatalf("PutNote: %v", err)
	}
	return updated
}

func (h *editHarness) get(userID, noteID string) model.NoteIndex {
	h.t.Helper()
	n, err := h.store.GetNote(h.ctx, userID, noteID)
	if err != nil {
		h.t.Fatalf("GetNote: %v", err)
	}
	return n
}

// Every body write marks an existing view stale; nothing else does.
func TestEditingTheBodyMarksTheCleanedViewStale(t *testing.T) {
	h := newEditHarness(t)
	n := h.withCleanedView("u", h.note("u", "Roof", "the gutter leaks"), false, "")

	version := n.Version
	title := "Roof repair"
	updated, err := h.notes.UpdateNote(h.ctx, "u", n.ID, NoteUpdates{Title: &title, ExpectedVersion: &version})
	if err != nil {
		t.Fatalf("UpdateNote(title): %v", err)
	}
	if updated.CleanedStale {
		t.Error("a title edit marked the view stale; only the body feeds the view")
	}
	if updated.CleanedBody == "" {
		t.Error("a title edit lost the cleaned body")
	}

	version = updated.Version
	body := "the gutter leaks badly"
	updated, err = h.notes.UpdateNote(h.ctx, "u", n.ID, NoteUpdates{Body: &body, ExpectedVersion: &version})
	if err != nil {
		t.Fatalf("UpdateNote(body): %v", err)
	}
	if !updated.CleanedStale {
		t.Error("a body edit did not mark the view stale")
	}
	if updated.CleanedBody != "# Cleaned\n\nThe view." {
		t.Errorf("a body edit changed the cleaned body itself: %q; the view is read-only and regenerated by the worker", updated.CleanedBody)
	}
}

func TestANoteWithoutAViewIsNeverStale(t *testing.T) {
	h := newEditHarness(t)
	n := h.note("u", "Roof", "the gutter leaks")
	version := n.Version
	body := "edited"
	updated, err := h.notes.UpdateNote(h.ctx, "u", n.ID, NoteUpdates{Body: &body, ExpectedVersion: &version})
	if err != nil {
		t.Fatalf("UpdateNote: %v", err)
	}
	if updated.CleanedStale {
		t.Error("a note that has never been cleaned was marked stale")
	}
}

func TestUpdateNoteStoresTheCleanPreferencesAndRefusesAnUnknownMode(t *testing.T) {
	h := newEditHarness(t)
	n := h.note("u", "Roof", "the gutter leaks")

	version := n.Version
	on, mode := true, model.NoteCleanPolished
	updated, err := h.notes.UpdateNote(h.ctx, "u", n.ID, NoteUpdates{AutoClean: &on, CleanMode: &mode, ExpectedVersion: &version})
	if err != nil {
		t.Fatalf("UpdateNote: %v", err)
	}
	if !updated.AutoClean || updated.CleanMode != model.NoteCleanPolished {
		t.Errorf("preferences not stored: auto_clean=%v mode=%q", updated.AutoClean, updated.CleanMode)
	}
	if updated.CleanedStale {
		t.Error("changing the preferences marked a non-existent view stale")
	}

	version = updated.Version
	bad := model.NoteCleanMode("faithful")
	if _, err := h.notes.UpdateNote(h.ctx, "u", n.ID, NoteUpdates{CleanMode: &bad, ExpectedVersion: &version}); !errors.Is(err, ErrInvalidNoteCleanMode) {
		t.Errorf("UpdateNote(cleaned_mode=faithful) = %v, want ErrInvalidNoteCleanMode", err)
	}
}

// Deleting a recording rewrites the body, so the view goes stale and, when the
// note asks, the worker is invoked — with the note's own mode, and only after
// the row is gone.
func TestDeletingARecordingMarksStaleAndAutoCleans(t *testing.T) {
	h := newEditHarness(t)
	worker := &stubInvoker{}
	h.captures.WithInvoker(worker)

	body := CaptureMarker("c_1") + "\nFirst take.\n\n" + CaptureMarker("c_2") + "\nSecond take."
	n := h.withCleanedView("u", h.note("u", "Roof", body), true, model.NoteCleanPolished)
	h.appended("u", n.ID, "c_1", "2026-01-01T09:00:00.000000000Z")
	h.appended("u", n.ID, "c_2", "2026-01-01T10:00:00.000000000Z")

	if err := h.captures.DeleteCapture(h.ctx, "u", "c_1"); err != nil {
		t.Fatalf("DeleteCapture: %v", err)
	}
	after := h.get("u", n.ID)
	if !after.CleanedStale {
		t.Error("deleting a recording did not mark the view stale")
	}
	if got := worker.calls; len(got) != 1 || got[0] != "clean-note/u/"+n.ID+"/polished" {
		t.Errorf("worker calls = %v, want one clean-note hand-off in the note's mode", got)
	}
}

func TestDeletingARecordingDoesNotAutoCleanANoteThatDidNotAsk(t *testing.T) {
	h := newEditHarness(t)
	worker := &stubInvoker{}
	h.captures.WithInvoker(worker)

	n := h.withCleanedView("u", h.note("u", "Roof", CaptureMarker("c_1")+"\nFirst take."), false, "")
	h.appended("u", n.ID, "c_1", "2026-01-01T09:00:00.000000000Z")
	if err := h.captures.DeleteCapture(h.ctx, "u", "c_1"); err != nil {
		t.Fatalf("DeleteCapture: %v", err)
	}
	if !h.get("u", n.ID).CleanedStale {
		t.Error("the view was not marked stale")
	}
	if len(worker.calls) != 0 {
		t.Errorf("worker was invoked %v for a note without auto_clean", worker.calls)
	}
}

// A move changes two bodies. Both views go stale, and each note that asked for
// it is regenerated — D2 said "structured mode re-runs on both notes".
func TestMovingARecordingMarksBothNotesStaleAndAutoCleansEach(t *testing.T) {
	h := newEditHarness(t)
	worker := &stubInvoker{}
	h.captures.WithInvoker(worker)

	source := h.withCleanedView("u", h.note("u", "Wrong", CaptureMarker("c_1")+"\nMisfiled."), true, model.NoteCleanStructured)
	target := h.withCleanedView("u", h.note("u", "Right", CaptureMarker("c_0")+"\nOriginal."), false, "")
	h.appended("u", source.ID, "c_1", "2026-01-01T09:00:00.000000000Z")
	h.appended("u", target.ID, "c_0", "2026-01-01T08:00:00.000000000Z")

	if _, moved, err := h.captures.MoveCapture(h.ctx, "u", "c_1", target.ID); err != nil || !moved {
		t.Fatalf("MoveCapture: moved=%v err=%v", moved, err)
	}
	if !h.get("u", source.ID).CleanedStale {
		t.Error("the source view was not marked stale")
	}
	if !h.get("u", target.ID).CleanedStale {
		t.Error("the target view was not marked stale")
	}
	if got := worker.calls; len(got) != 1 || got[0] != "clean-note/u/"+source.ID+"/structured" {
		t.Errorf("worker calls = %v, want exactly the source (the note that asked)", got)
	}
}

// The request path checks the note and invokes; it never runs the model.
func TestRequestCleanChecksTheNoteAndInvokesTheWorker(t *testing.T) {
	h := newEditHarness(t)
	worker := &stubInvoker{}
	h.notes.WithInvoker(worker)
	n := h.note("u", "Roof", "the gutter leaks")

	mode, err := h.notes.RequestClean(h.ctx, "u", n.ID, "")
	if err != nil {
		t.Fatalf("RequestClean: %v", err)
	}
	if mode != model.NoteCleanStructured {
		t.Errorf("default mode = %q, want structured", mode)
	}
	if _, err := h.notes.RequestClean(h.ctx, "u", n.ID, model.NoteCleanPolished); err != nil {
		t.Fatalf("RequestClean(polished): %v", err)
	}
	if got := strings.Join(worker.calls, ","); got != "clean-note/u/"+n.ID+"/structured,clean-note/u/"+n.ID+"/polished" {
		t.Errorf("worker calls = %v", worker.calls)
	}

	// The note's own preference is the default once set.
	stored := h.get("u", n.ID)
	stored.CleanMode = model.NoteCleanPolished
	if _, err := h.store.PutNote(h.ctx, "u", stored); err != nil {
		t.Fatalf("PutNote: %v", err)
	}
	if mode, err := h.notes.RequestClean(h.ctx, "u", n.ID, ""); err != nil || mode != model.NoteCleanPolished {
		t.Errorf("RequestClean with a stored preference = %q, %v; want polished", mode, err)
	}

	if _, err := h.notes.RequestClean(h.ctx, "u", n.ID, model.NoteCleanMode("faithful")); !errors.Is(err, ErrInvalidNoteCleanMode) {
		t.Errorf("RequestClean(faithful) = %v, want ErrInvalidNoteCleanMode", err)
	}
	if _, err := h.notes.RequestClean(h.ctx, "u", "missing", ""); err == nil {
		t.Error("RequestClean on a missing note succeeded")
	}

	if _, err := h.notes.ArchiveNote(h.ctx, "u", n.ID); err != nil {
		t.Fatalf("ArchiveNote: %v", err)
	}
	if _, err := h.notes.RequestClean(h.ctx, "u", n.ID, ""); !errors.Is(err, ErrNoteArchived) {
		t.Errorf("RequestClean on an archived note = %v, want ErrNoteArchived", err)
	}
}

func TestRequestCleanWithoutAWorkerSaysSo(t *testing.T) {
	store, objects := memory.NewStore(), memory.NewObjects()
	notes := NewNotesService(store, objects)
	n, err := notes.CreateNote(context.Background(), "u", "Roof", nil)
	if err != nil {
		t.Fatalf("CreateNote: %v", err)
	}
	if _, err := notes.RequestClean(context.Background(), "u", n.ID, ""); !errors.Is(err, ErrCaptureWorkerUnavailable) {
		t.Errorf("RequestClean without a worker = %v, want ErrCaptureWorkerUnavailable", err)
	}
}

// Two requests for the same mode inside the worker's window are one run: the
// second answers as queued and hands nothing to the worker. The other mode is
// a different answer and goes through; a stamp older than the worker's window
// belongs to a run that died, and the next request invokes again.
func TestRequestCleanJoinsARunInFlightAndReinvokesOnlyForAnotherModeOrAStaleStamp(t *testing.T) {
	h := newEditHarness(t)
	worker := &stubInvoker{}
	now := time.Date(2026, 9, 5, 14, 34, 0, 0, time.UTC)
	h.notes.WithInvoker(worker).WithClock(func() time.Time { return now })
	n := h.note("u", "Roof", "the gutter leaks")

	for i := 0; i < 2; i++ {
		mode, err := h.notes.RequestClean(h.ctx, "u", n.ID, model.NoteCleanStructured)
		if err != nil || mode != model.NoteCleanStructured {
			t.Fatalf("request %d: mode=%q err=%v; a repeat is answered as queued", i+1, mode, err)
		}
	}
	if got := worker.calls; len(got) != 1 {
		t.Fatalf("worker calls = %v, want exactly one hand-off for two rapid requests in the same mode", got)
	}
	stamped := h.get("u", n.ID)
	if stamped.CleanedRequestedMode != model.NoteCleanStructured || stamped.CleanedRequestedAt != model.FormatTime(now) {
		t.Errorf("stamp = %q at %q, want structured at %s", stamped.CleanedRequestedMode, stamped.CleanedRequestedAt, model.FormatTime(now))
	}

	now = now.Add(30 * time.Second)
	if _, err := h.notes.RequestClean(h.ctx, "u", n.ID, model.NoteCleanPolished); err != nil {
		t.Fatalf("RequestClean(polished): %v", err)
	}
	if got := worker.calls; len(got) != 2 || got[1] != "clean-note/u/"+n.ID+"/polished" {
		t.Fatalf("worker calls = %v, want the other mode handed over as a second run", got)
	}
	if got := h.get("u", n.ID).CleanedRequestedMode; got != model.NoteCleanPolished {
		t.Errorf("stamp mode = %q after the polished request, want polished", got)
	}

	// The same mode again, but past the window: the stamp was left by a run
	// that never reached a verdict.
	now = now.Add(CleanNoteTimeout)
	if _, err := h.notes.RequestClean(h.ctx, "u", n.ID, model.NoteCleanPolished); err != nil {
		t.Fatalf("RequestClean(stale): %v", err)
	}
	if got := worker.calls; len(got) != 3 {
		t.Fatalf("worker calls = %v, want a third hand-off once the stamp is older than the worker's window", got)
	}
}

// The auto-clean path stamps too, so the worker can tell a run the body has
// since outdated from the one it was invoked for.
func TestAutoCleanStampsTheRequestItHandsOver(t *testing.T) {
	h := newEditHarness(t)
	worker := &stubInvoker{}
	h.captures.WithInvoker(worker)

	body := CaptureMarker("c_1") + "\nFirst take.\n\n" + CaptureMarker("c_2") + "\nSecond take."
	n := h.withCleanedView("u", h.note("u", "Roof", body), true, model.NoteCleanPolished)
	h.appended("u", n.ID, "c_1", "2026-01-01T09:00:00.000000000Z")
	h.appended("u", n.ID, "c_2", "2026-01-01T10:00:00.000000000Z")
	if err := h.captures.DeleteCapture(h.ctx, "u", "c_1"); err != nil {
		t.Fatalf("DeleteCapture: %v", err)
	}
	after := h.get("u", n.ID)
	if after.CleanedRequestedMode != model.NoteCleanPolished || after.CleanedRequestedAt == "" {
		t.Errorf("stamp after an auto-clean hand-off = %q at %q, want polished with a time", after.CleanedRequestedMode, after.CleanedRequestedAt)
	}
	if len(worker.calls) != 1 {
		t.Errorf("worker calls = %v", worker.calls)
	}
}

// Recording a clean request is not a content write. It must not move the
// version — an autosave already on the wire would lose its version check for
// nothing — and it must not rewrite the row from the caller's copy: the notes
// list omits cleaned_body, and a request recorded from a listed note used to
// write the view away.
func TestRecordCleanRequestMovesNeitherTheVersionNorTheCleanedView(t *testing.T) {
	h := newEditHarness(t)
	n := h.withCleanedView("u", h.note("u", "Roof", "the gutter leaks"), false, model.NoteCleanPolished)
	before := h.get("u", n.ID)
	if before.CleanedBody == "" {
		t.Fatal("the fixture has no cleaned view; the test cannot show it survives")
	}

	// The caller's copy is a listed note: everything but the view.
	listed := before
	listed.CleanedBody = ""
	stamped, inFlight, err := RecordCleanRequest(h.ctx, h.store, "u", listed, model.NoteCleanStructured, time.Date(2026, 9, 5, 15, 0, 0, 0, time.UTC), true)
	if err != nil || inFlight {
		t.Fatalf("RecordCleanRequest: inFlight=%v err=%v", inFlight, err)
	}
	if stamped.Version != before.Version {
		t.Errorf("version moved from %d to %d for a request; the version is for content writes", before.Version, stamped.Version)
	}
	after := h.get("u", n.ID)
	if after.CleanedBody != before.CleanedBody {
		t.Errorf("cleaned view after the request = %q, want the stored view %q untouched", after.CleanedBody, before.CleanedBody)
	}
	if after.CleanedRequestedMode != model.NoteCleanStructured || after.CleanedRequestedAt == "" {
		t.Errorf("stamp = %q at %q", after.CleanedRequestedMode, after.CleanedRequestedAt)
	}

	// A stale caller re-reads and stamps again rather than failing.
	stale := before
	stale.Version = before.Version - 1
	if _, _, err := RecordCleanRequest(h.ctx, h.store, "u", stale, model.NoteCleanPolished, time.Date(2026, 9, 5, 15, 1, 0, 0, time.UTC), false); err != nil {
		t.Fatalf("RecordCleanRequest(stale copy): %v", err)
	}
	if got := h.get("u", n.ID).CleanedRequestedMode; got != model.NoteCleanPolished {
		t.Errorf("stamp mode after the re-read = %q, want polished", got)
	}

	// Clearing takes back only the stamp the failed hand-off wrote.
	current := h.get("u", n.ID)
	older := current
	older.CleanedRequestedAt = "2026-09-05T14:00:00.000000000Z"
	ClearCleanRequest(h.ctx, h.store, "u", older)
	if got := h.get("u", n.ID).CleanedRequestedAt; got != current.CleanedRequestedAt {
		t.Errorf("a clear for an older stamp removed the current one")
	}
	ClearCleanRequest(h.ctx, h.store, "u", current)
	if got := h.get("u", n.ID); got.CleanedRequestedAt != "" || got.Version != current.Version {
		t.Errorf("after the clear: stamp=%q version=%d, want empty and %d", got.CleanedRequestedAt, got.Version, current.Version)
	}
}
