package service

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/vppillai/chintan/backend/internal/keys"
	"github.com/vppillai/chintan/backend/internal/match"
	"github.com/vppillai/chintan/backend/internal/model"
	"github.com/vppillai/chintan/backend/internal/obs"
	"github.com/vppillai/chintan/backend/internal/repository"
)

const ArchiveRetention = 30 * 24 * time.Hour

// maxNoteTitleLen bounds a stored title. It matches the OpenAPI document's
// maxLength for a note title, so a title the API accepts is a title that is
// stored whole. Two different limits for one field means a request the handler
// validated is quietly truncated by the service, which is data loss with a
// receipt.
//
// The routing prompt does not depend on this number: it bounds every rendered
// candidate field itself (routing.maxFieldLen), so a longer stored title cannot
// grow the prompt.
const maxNoteTitleLen = 200

var (
	ErrNoteArchived    = errors.New("note is archived")
	ErrNoteNotArchived = errors.New("note is not archived")
	ErrEmptyNoteTitle  = errors.New("note title is empty")
	// ErrPurgeIncomplete means part of a permanent delete failed. The note index
	// is deliberately left in place so the delete can be retried, because
	// reporting "purged" while audio survives in S3 is worse than reporting a
	// failure.
	ErrPurgeIncomplete = errors.New("note purge incomplete")
)

// maxMatchCandidates bounds how many notes note-matching will page through.
const maxMatchCandidates = 500

// sanitizeNoteTitle collapses a title to a single bounded line.
func sanitizeNoteTitle(title string) string {
	title = strings.Map(func(r rune) rune {
		if unicode.IsControl(r) {
			return ' '
		}
		return r
	}, title)
	title = strings.Join(strings.Fields(title), " ")
	if runes := []rune(title); len(runes) > maxNoteTitleLen {
		title = strings.TrimSpace(string(runes[:maxNoteTitleLen]))
	}
	return title
}

func NoteIsActive(n model.NoteIndex) bool {
	return strings.TrimSpace(n.DeletedAt) == ""
}

// maxTagLen bounds one tag. Tags are rendered into list filters and into the
// routing prompt, so an unbounded tag is a stored cost amplifier.
const maxTagLen = 40

// normalizeTags folds tags to a canonical form: trimmed, lowercased, collapsed
// whitespace, deduplicated, ordered. Without this "Roof", "roof " and "roof"
// are three tags in the index and one tag to the person who said them.
func normalizeTags(tags []string) []string {
	if len(tags) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(tags))
	out := make([]string, 0, len(tags))
	for _, raw := range tags {
		t := strings.ToLower(strings.Join(strings.Fields(raw), " "))
		if t == "" {
			continue
		}
		if runes := []rune(t); len(runes) > maxTagLen {
			t = strings.TrimSpace(string(runes[:maxTagLen]))
		}
		if _, dup := seen[t]; dup {
			continue
		}
		seen[t] = struct{}{}
		out = append(out, t)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return nil
	}
	return out
}

// NotesService handles note operations
type NotesService struct {
	store   repository.Store
	objects repository.Objects
	// worker is the hand-off for the clean-note task. Nil means POST
	// /v1/notes/{id}/clean answers 503 and auto-clean logs and skips.
	worker Invoker
}

// NoteUpdates represents partial updates to a note.
//
// ExpectedVersion is the version the client read. It is compared before
// anything is written, so a voice append landing while the editor is open
// surfaces as a conflict the client reconciles rather than one of the two
// writes vanishing. A nil ExpectedVersion skips the check and is for in-process
// callers only — every HTTP caller supplies one.
type NoteUpdates struct {
	Title    *string
	Aliases  *[]string
	Tags     *[]string
	Body     *string
	Verbatim *bool
	// Language is the transcription language for captures recorded into this
	// note: model.LanguageAuto, an ISO-639-1 code, or "" to fall back to the
	// tenant's default. Validated here, not only at the handler, because the
	// worker passes it straight to the provider.
	Language *string
	// AutoClean and CleanMode are the whole-note cleaned view's preferences
	// (note_clean.go). The view itself is not here: it is read-only from the
	// API and regenerated by the worker.
	AutoClean       *bool
	CleanMode       *model.NoteCleanMode
	ExpectedVersion *int64
}

// MatchResult represents the result of a note matching operation
type MatchResult struct {
	Candidates   []match.Candidate `json:"candidates"`
	AutoSelectID *string           `json:"auto_select_id,omitempty"`
}

// NewNotesService creates a new notes service
func NewNotesService(store repository.Store, objects repository.Objects) *NotesService {
	return &NotesService{
		store:   store,
		objects: objects,
	}
}

// CreateNote creates a new note.
//
// The signature is what the worker's NoteCreator expects; CreateNoteWithTags is
// the fuller form the API uses.
func (s *NotesService) CreateNote(ctx context.Context, userID, title string, aliases []string) (model.NoteIndex, error) {
	return s.CreateNoteWithTags(ctx, userID, title, aliases, nil)
}

// CreateNoteWithTags creates a note carrying tags.
func (s *NotesService) CreateNoteWithTags(ctx context.Context, userID, title string, aliases, tags []string) (model.NoteIndex, error) {
	title = sanitizeNoteTitle(title)
	if title == "" {
		return model.NoteIndex{}, ErrEmptyNoteTitle
	}

	noteIDBytes := make([]byte, 8)
	if _, err := rand.Read(noteIDBytes); err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to generate note ID: %w", err)
	}
	// Same shape as a capture id: a fixed-width creation instant so ids sort
	// chronologically — the note index is keyed NOTE#<id>, so the id is what
	// decides list order — followed by random bytes. The clock alone is both
	// guessable from the creation time and collision-prone, and a collision
	// surfaces to the user as an unexplained 409 on a note they just made.
	noteID := fmt.Sprintf("note_%016x_%s",
		uint64(time.Now().UTC().UnixNano()), hex.EncodeToString(noteIDBytes))

	// Generate S3 keys
	markdownKey, err := keys.NoteMarkdown(userID, noteID)
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to generate markdown key: %w", err)
	}

	metaKey, err := keys.NoteMeta(userID, noteID)
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to generate meta key: %w", err)
	}

	if aliases == nil {
		aliases = []string{}
	}

	now := model.Now()
	note := model.NoteIndex{
		ID:            noteID,
		Title:         title,
		Aliases:       aliases,
		Tags:          normalizeTags(tags),
		Snippet:       "", // No content initially
		SearchText:    "",
		CreatedAt:     now,
		UpdatedAt:     now,
		S3MarkdownKey: markdownKey,
		S3MetaKey:     metaKey,
	}

	// Create initial empty markdown file
	err = s.objects.Put(ctx, markdownKey, []byte(""), "text/markdown")
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to create markdown file: %w", err)
	}

	// Create metadata file
	metaData := map[string]interface{}{
		"title":      title,
		"aliases":    aliases,
		"tags":       note.Tags,
		"created_at": note.CreatedAt,
		"updated_at": note.UpdatedAt,
	}
	metaBytes, _ := json.Marshal(metaData)
	err = s.objects.Put(ctx, metaKey, metaBytes, "application/json")
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to create meta file: %w", err)
	}

	// Save to store
	stored, err := s.store.PutNote(ctx, userID, note)
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to save note: %w", err)
	}

	return stored, nil
}

// ListNotes returns one page of active notes. Archived notes are excluded by
// the store, so the filtering is no longer paid for in Go.
func (s *NotesService) ListNotes(ctx context.Context, userID string, opts repository.ListOptions) (repository.Page[model.NoteIndex], error) {
	return s.store.ListNotes(ctx, userID, opts)
}

// GetNote retrieves a specific note
func (s *NotesService) GetNote(ctx context.Context, userID, noteID string) (model.NoteIndex, error) {
	return s.store.GetNote(ctx, userID, noteID)
}

// NoteDetail is a note index plus markdown body for the editor.
type NoteDetail struct {
	model.NoteIndex
	Body string `json:"body"`
}

// GetNoteDetail retrieves a note and its markdown body from object storage.
func (s *NotesService) GetNoteDetail(ctx context.Context, userID, noteID string) (NoteDetail, error) {
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return NoteDetail{}, err
	}
	bodyBytes, err := s.objects.Get(ctx, note.S3MarkdownKey)
	if err != nil && !errors.Is(err, repository.ErrNotFound) {
		return NoteDetail{}, fmt.Errorf("failed to load note body: %w", err)
	}
	// The worker's append markers stay in the object and out of the editor;
	// UpdateNote puts them back. See note_markers.go.
	return NoteDetail{NoteIndex: note, Body: StripCaptureMarkers(string(bodyBytes))}, nil
}

// UpdateNote updates a note with partial changes
func (s *NotesService) UpdateNote(ctx context.Context, userID, noteID string, updates NoteUpdates) (model.NoteIndex, error) {
	// Get existing note
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return model.NoteIndex{}, err
	}

	// Check if note is archived
	if !NoteIsActive(note) {
		return model.NoteIndex{}, ErrNoteArchived
	}

	// Read the body's ETag before the version check, so the conditional write
	// below covers the whole of this call. The pipeline's append writes the
	// object first and refreshes the index afterwards, so an append that lands
	// after the version check is invisible to it — only the ETag catches it.
	//
	// The stored body is kept as well as its ETag: the client never saw the
	// worker's append markers (GetNoteDetail strips them), so they are put
	// back onto whatever it sends, or a save inside a capture's retry window
	// would erase the one fact that stops the retry appending twice.
	bodyETag := ""
	var storedBody []byte
	if updates.Body != nil {
		storedBody, bodyETag, err = s.objects.GetWithETag(ctx, note.S3MarkdownKey)
		if err != nil && !errors.Is(err, repository.ErrNotFound) {
			return model.NoteIndex{}, fmt.Errorf("failed to read note body: %w", err)
		}
	}

	// The version the client read is checked before anything is written, which
	// rejects the common conflict cheaply. It cannot close the window on its
	// own: an append landing after this line and before the write below is
	// caught by the ETag, not by this.
	if updates.ExpectedVersion != nil && *updates.ExpectedVersion != note.Version {
		return note, repository.ErrVersionConflict
	}

	// Apply updates
	if updates.Title != nil {
		title := sanitizeNoteTitle(*updates.Title)
		if title == "" {
			return model.NoteIndex{}, ErrEmptyNoteTitle
		}
		note.Title = title
	}
	if updates.Aliases != nil {
		note.Aliases = *updates.Aliases
	}
	if updates.Tags != nil {
		note.Tags = normalizeTags(*updates.Tags)
	}
	if updates.Verbatim != nil {
		note.Verbatim = *updates.Verbatim
	}
	if updates.Language != nil {
		lang := strings.ToLower(strings.TrimSpace(*updates.Language))
		if lang != "" && !model.ValidLanguage(lang) {
			return model.NoteIndex{}, ErrInvalidLanguage
		}
		note.Language = lang
	}
	if updates.AutoClean != nil {
		note.AutoClean = *updates.AutoClean
	}
	if updates.CleanMode != nil {
		if !model.ValidNoteCleanMode(*updates.CleanMode) {
			return model.NoteIndex{}, ErrInvalidNoteCleanMode
		}
		note.CleanMode = *updates.CleanMode
	}

	// Update timestamp
	note.UpdatedAt = model.Now()

	// Handle body update
	if updates.Body != nil {
		// Write to markdown file, conditional on the object still carrying the
		// ETag read above. An unconditional Put here destroys a voice append
		// that landed in the meantime and only then reports the conflict — the
		// client is told to re-read text that no longer exists anywhere.
		body := CarryCaptureMarkers(string(storedBody), *updates.Body)
		err = s.objects.PutIfMatch(ctx, note.S3MarkdownKey, []byte(body), "text/markdown", bodyETag)
		if errors.Is(err, repository.ErrPreconditionFailed) {
			// Somebody else wrote the body between the read and this write.
			// That is the same 409 the version check answers, and the client
			// reconciles it the same way.
			return note, repository.ErrVersionConflict
		}
		if err != nil {
			return model.NoteIndex{}, fmt.Errorf("failed to update markdown: %w", err)
		}

		// Update snippet (first ~500 chars) and the search text, which are the
		// two derivations of the body the index row carries.
		note.Snippet = generateSnippet(*updates.Body)
		note.SearchText = SearchText(*updates.Body)
		// The cleaned view was generated from the body that just changed.
		MarkCleanedStale(&note)
	}

	// Update metadata
	metaData := map[string]interface{}{
		"title":      note.Title,
		"aliases":    note.Aliases,
		"tags":       note.Tags,
		"verbatim":   note.Verbatim,
		"language":   note.Language,
		"updated_at": note.UpdatedAt,
	}
	metaBytes, _ := json.Marshal(metaData)
	err = s.objects.Put(ctx, note.S3MetaKey, metaBytes, "application/json")
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to update meta: %w", err)
	}

	// Save to store. A version conflict here means somebody else wrote the note
	// between the read and this write; the caller reconciles rather than one of
	// the two edits vanishing.
	stored, err := s.store.PutNote(ctx, userID, note)
	if err != nil {
		return model.NoteIndex{}, err
	}

	return stored, nil
}

// DeleteNote archives a note (soft delete)
func (s *NotesService) DeleteNote(ctx context.Context, userID, noteID string) error {
	_, err := s.ArchiveNote(ctx, userID, noteID)
	return err
}

// MatchNotes finds matching notes for a query (only searches active notes)
func (s *NotesService) MatchNotes(ctx context.Context, userID, query string) (MatchResult, error) {
	// Matching scores against every candidate, so it pages through the whole
	// active set rather than seeing whatever fitted in one page.
	notes, err := repository.DrainPages(ctx, maxMatchCandidates, func(ctx context.Context, opts repository.ListOptions) (repository.Page[model.NoteIndex], error) {
		return s.store.ListNotes(ctx, userID, opts)
	})
	if err != nil {
		return MatchResult{}, err
	}

	// Rank all candidates first (following binding decision #1)
	candidates := match.Rank(query, notes, 0) // 0 means no limit, get all

	// Check for high confidence
	highConfidence := match.HighConfidence(candidates)

	// Limit response to reasonable number for UI
	if len(candidates) > 10 {
		candidates = candidates[:10]
	}

	result := MatchResult{
		Candidates: candidates,
	}

	// Set auto_select_id only for high confidence matches
	if highConfidence && len(candidates) > 0 {
		result.AutoSelectID = &candidates[0].NoteID
	}

	return result, nil
}

// generateSnippet creates a snippet from a note body.
//
// The cut is by rune, not byte. A byte slice cuts multi-byte runes in half and
// writes invalid UTF-8 into DynamoDB and into the routing prompt.
//
// The worker's append markers are removed first: the snippet is shown in the
// notes list and handed to the router as a summary of the note, and neither
// wants an HTML comment in it.
func generateSnippet(body string) string {
	const maxRunes = 500
	body = StripCaptureMarkers(body)
	runes := []rune(body)
	if len(runes) <= maxRunes {
		return body
	}
	return string(runes[:maxRunes]) + "..."
}

// ArchiveNote archives a note (soft delete with retention period)
func (s *NotesService) ArchiveNote(ctx context.Context, userID, noteID string) (model.NoteIndex, error) {
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return model.NoteIndex{}, err
	}

	// If already archived, return as-is (idempotent)
	if !NoteIsActive(note) {
		return note, nil
	}

	// Set archive timestamps. PurgeAfterEpoch is the deadline the archived list
	// filters on and the weekly expiry sweep (internal/purge) collects on; the
	// store derives the DynamoDB TTL backstop from it. Nothing sweeps on read.
	now := time.Now().UTC()
	purgeAt := now.Add(ArchiveRetention)
	note.DeletedAt = model.FormatTime(now)
	note.PurgeAfter = model.FormatTime(purgeAt)
	note.PurgeAfterEpoch = purgeAt.Unix()

	// Save updated note
	stored, err := s.store.PutNote(ctx, userID, note)
	if err != nil {
		return model.NoteIndex{}, err
	}

	return stored, nil
}

// RestoreNote restores an archived note to active status
func (s *NotesService) RestoreNote(ctx context.Context, userID, noteID string) (model.NoteIndex, error) {
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return model.NoteIndex{}, err
	}

	// If already active, return as-is (idempotent)
	if NoteIsActive(note) {
		return note, nil
	}

	// Clear archive fields, including the TTL, so the table stops counting down.
	note.DeletedAt = ""
	note.PurgeAfter = ""
	note.PurgeAfterEpoch = 0

	// Save updated note
	stored, err := s.store.PutNote(ctx, userID, note)
	if err != nil {
		return model.NoteIndex{}, err
	}

	return stored, nil
}

// ListArchivedNotes returns one page of archived notes that have not passed
// their purge deadline. Expiry itself belongs to DynamoDB TTL; the filter only
// keeps an item the table has not collected yet out of the UI.
func (s *NotesService) ListArchivedNotes(ctx context.Context, userID string, opts repository.ListOptions) (repository.Page[model.NoteIndex], error) {
	return s.store.ListArchivedNotes(ctx, userID, opts)
}

// PermanentlyDeleteNote permanently deletes an archived note and all its captures
func (s *NotesService) PermanentlyDeleteNote(ctx context.Context, userID, noteID string) error {
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return err
	}

	// Must be archived first
	if NoteIsActive(note) {
		return ErrNoteNotArchived
	}

	return s.hardDeleteNote(ctx, userID, noteID, note)
}

// hardDeleteNote removes a note's captures, its objects, and finally its index.
//
// It fails loudly. Logging a cascade failure and deleting the index anyway
// permanently orphans audio the UI has reported as purged. Here the index
// survives any failure, so the note stays visible as archived and the delete
// can be retried.
func (s *NotesService) hardDeleteNote(ctx context.Context, userID, noteID string, note model.NoteIndex) error {
	if err := s.PurgeNoteArtifacts(ctx, userID, noteID, note); err != nil {
		return err
	}
	return s.store.DeleteNote(ctx, userID, noteID)
}

// PurgeNoteArtifacts unlinks everything a note owns apart from its own index
// row: every capture filed against it, every S3 object those captures name, and
// the note's own body and metadata.
//
// It is separate from hardDeleteNote because the same cascade has to run from
// two places that disagree about whether the index row still exists. A user
// asking to delete forever arrives through hardDeleteNote, which removes the row
// last so a failed cascade leaves the note visible and retryable. DynamoDB TTL
// arrives through internal/purge, by which point the row is already gone and
// there is nothing left to delete — only the objects it named, which is exactly
// this. Before that handler existed, TTL removed the index row and left the
// audio, raw transcript, routed transcript, cleaned text, segments and peaks in
// the bucket, billed and unreachable, with `chintanctl reconcile` as the only
// way to find them.
//
// Every failure is returned rather than logged, so a caller that must not
// declare a purge complete can tell that it is not.
func (s *NotesService) PurgeNoteArtifacts(ctx context.Context, userID, noteID string, note model.NoteIndex) error {
	// Every page, not just the first: a truncated list is how "delete forever"
	// leaves orphans behind.
	captures, err := repository.DrainPages(ctx, 0, func(ctx context.Context, opts repository.ListOptions) (repository.Page[model.CaptureIndex], error) {
		return s.store.ListCapturesByNote(ctx, userID, noteID, opts)
	})
	if err != nil {
		return fmt.Errorf("%w: list captures: %w", ErrPurgeIncomplete, err)
	}

	for _, c := range captures {
		// Every object the capture may own, including a peaks key the row no
		// longer records; see captureObjectKeys.
		for _, key := range captureObjectKeys(userID, c) {
			if err := s.deleteObject(ctx, key); err != nil {
				return fmt.Errorf("%w: capture %s object: %w", ErrPurgeIncomplete, c.ID, err)
			}
		}
		if err := s.store.DeleteCapture(ctx, userID, c.ID); err != nil && !errors.Is(err, repository.ErrNotFound) {
			return fmt.Errorf("%w: capture %s index: %w", ErrPurgeIncomplete, c.ID, err)
		}
	}

	if err := s.deleteObject(ctx, note.S3MarkdownKey); err != nil {
		return fmt.Errorf("%w: note body: %w", ErrPurgeIncomplete, err)
	}
	if err := s.deleteObject(ctx, note.S3MetaKey); err != nil {
		return fmt.Errorf("%w: note meta: %w", ErrPurgeIncomplete, err)
	}

	return nil
}

// deleteObject removes a key, treating "already gone" as success so a retried
// purge can make progress.
func (s *NotesService) deleteObject(ctx context.Context, key string) error {
	return deleteObjectIfPresent(ctx, s.objects, key)
}

// MaxPurgeBatch bounds one batch purge.
//
// It keeps the work per request bounded and inside the API Lambda's 29-second
// ceiling: a purge is not one delete but a cascade over every capture of every
// note named, and each capture unlinks six objects. A hundred notes with a
// handful of captures each is already several hundred S3 calls. "Clear all" is
// the client listing its archive and sending it in batches, which is also why
// there is deliberately no "purge everything" switch — a flag like that is one
// malformed request away from emptying an account, and nothing here needs it.
const MaxPurgeBatch = 100

// Purge outcomes. They are stable strings because a client branches on them.
const (
	// PurgeStatusPurged means the note and everything it owned are gone.
	PurgeStatusPurged = "purged"
	// PurgeStatusNotFound means there was no such note. Replaying a batch that
	// already succeeded reports this, which is what makes a retry safe.
	PurgeStatusNotFound = "not_found"
	// PurgeStatusFailed means the note is still there. Either it was not
	// archived — refusing that is what stops a stale client turning "clear my
	// archive" into "delete my notes" — or part of its cascade failed, in which
	// case the index row is deliberately left so the delete can be retried.
	PurgeStatusFailed = "failed"
)

// PurgeResult is one note's outcome. Detail is written for a person and never
// carries infrastructure text.
type PurgeResult struct {
	NoteID string `json:"note_id"`
	Status string `json:"status"`
	Detail string `json:"detail,omitempty"`
}

// ErrPurgeBatchTooLarge rejects a batch above MaxPurgeBatch.
var ErrPurgeBatchTooLarge = errors.New("too many notes in one purge")

// ErrPurgeBatchEmpty rejects a batch naming nothing.
var ErrPurgeBatchEmpty = errors.New("no notes named")

// PurgeNotes permanently deletes several archived notes and reports each
// outcome separately.
//
// It is not all-or-nothing, and it does not pretend to be. There is no
// transaction spanning DynamoDB and S3, so a batch that reported a single
// success or failure would be lying about the notes on the other side of the
// first problem; the client is told what happened to each and can show what
// survived.
//
// One note's failure never stops the batch. The alternative — abandoning the
// rest — turns a single unlinkable object into a purge the user has to retry
// from the beginning, repeatedly, with a different note failing each time.
func (s *NotesService) PurgeNotes(ctx context.Context, userID string, noteIDs []string) ([]PurgeResult, error) {
	switch {
	case len(noteIDs) == 0:
		return nil, ErrPurgeBatchEmpty
	case len(noteIDs) > MaxPurgeBatch:
		return nil, ErrPurgeBatchTooLarge
	}

	results := make([]PurgeResult, 0, len(noteIDs))
	// A batch may name the same note twice — a client assembling "clear all"
	// from overlapping pages will. Purging it once and reporting the second as
	// already gone is honest; running the cascade twice is wasted work.
	seen := make(map[string]bool, len(noteIDs))

	for _, noteID := range noteIDs {
		if seen[noteID] {
			results = append(results, PurgeResult{
				NoteID: noteID, Status: PurgeStatusNotFound,
				Detail: "named more than once in this batch",
			})
			continue
		}
		seen[noteID] = true
		results = append(results, s.purgeOne(ctx, userID, noteID))
	}
	return results, nil
}

// purgeOne is PermanentlyDeleteNote with its errors turned into an outcome
// rather than a failure of the whole request.
func (s *NotesService) purgeOne(ctx context.Context, userID, noteID string) PurgeResult {
	note, err := s.store.GetNote(ctx, userID, noteID)
	switch {
	case errors.Is(err, repository.ErrNotFound):
		// Already gone, or never existed, or belongs to another tenant — the
		// store cannot tell those apart from here and must not, since the
		// answer would confirm another tenant's identifier.
		return PurgeResult{NoteID: noteID, Status: PurgeStatusNotFound, Detail: "no such note"}
	case err != nil:
		return PurgeResult{
			NoteID: noteID, Status: PurgeStatusFailed,
			Detail: "the note could not be read; nothing was deleted",
		}
	}

	if NoteIsActive(note) {
		// The refusal that matters. A client working from a stale archive
		// listing would otherwise turn "clear my archive" into "delete the
		// notes I am still using", and a purge is not reversible.
		return PurgeResult{
			NoteID: noteID, Status: PurgeStatusFailed,
			Detail: "this note is not archived, so it was not deleted; archive it first",
		}
	}

	if err := s.hardDeleteNote(ctx, userID, noteID, note); err != nil {
		// The index row survives a failed cascade by design, so the note is
		// still listed as archived and the purge can be retried. Reporting
		// success here would leave audio in the bucket that the UI had already
		// said was deleted.
		//
		// The detail is fixed text: the underlying error carries bucket and
		// table names, and it is logged rather than returned.
		obs.Log(ctx).Error("batch purge could not finish a note",
			slog.String("note_id", noteID), slog.String("error", err.Error()))
		return PurgeResult{
			NoteID: noteID, Status: PurgeStatusFailed,
			Detail: "some of this note's files could not be removed; it is still here and can be deleted again",
		}
	}

	return PurgeResult{NoteID: noteID, Status: PurgeStatusPurged}
}
