package service

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"github.com/vppillai/chintan/backend/internal/model"
	"github.com/vppillai/chintan/backend/internal/obs"
)

// The whole-note cleaned view (backlog D1).
//
// Every recording has a cleaned and a timestamped view of its own transcript.
// The cleaned view is one pass over the ENTIRE note body — headings, lists,
// coherent prose — generated by the worker's clean-note task on request
// (POST /v1/notes/{id}/clean) or, when the note has auto_clean, after every
// change to the body the system makes: an append, a recording moved in or
// out, a recording deleted.
//
// Two rules hold everywhere the body is written:
//
//   - The view is READ-ONLY from the API. It is derived from the body, so an
//     edit belongs in the body and the view is regenerated from it; there is
//     no endpoint that writes cleaned_body, and PATCH does not accept one.
//   - Every body write marks an existing view stale (MarkCleanedStale). The
//     worker clears the flag when it regenerates the view from the current
//     body, and only then.
//
// The LLM call itself never runs on the request path. The API and the request
// half of the capture service only ever invoke the worker asynchronously.

// ErrInvalidNoteCleanMode rejects a mode outside polished and structured.
var ErrInvalidNoteCleanMode = errors.New("cleaned_mode must be polished or structured")

// MarkCleanedStale records that the body has changed since the cleaned view
// was generated. A note with no view has nothing to be stale.
func MarkCleanedStale(n *model.NoteIndex) {
	if n.CleanedBody != "" || n.CleanedAt != "" {
		n.CleanedStale = true
	}
}

// EffectiveCleanMode is the mode an automatic or unspecified clean of n runs in.
func EffectiveCleanMode(n model.NoteIndex) model.NoteCleanMode {
	if model.ValidNoteCleanMode(n.CleanMode) {
		return n.CleanMode
	}
	return model.DefaultNoteCleanMode
}

// WithInvoker installs the hand-off to the worker Lambda, which is where the
// clean-note task runs.
func (s *NotesService) WithInvoker(w Invoker) *NotesService {
	s.worker = w
	return s
}

// RequestClean asks the worker to regenerate noteID's cleaned view in mode, or
// in the note's own mode when mode is empty, and returns the mode that was
// queued. It reads nothing from object storage and calls no provider: the
// request path's whole job is to check the note and invoke the worker.
//
// A second request while one is queued is fine. The worker regenerates from
// the body as it stands when it runs, so two runs produce the same view and
// the later one simply wins.
func (s *NotesService) RequestClean(ctx context.Context, userID, noteID string, mode model.NoteCleanMode) (model.NoteCleanMode, error) {
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return "", err
	}
	if !NoteIsActive(note) {
		return "", ErrNoteArchived
	}
	if mode == "" {
		mode = EffectiveCleanMode(note)
	}
	if !model.ValidNoteCleanMode(mode) {
		return "", ErrInvalidNoteCleanMode
	}
	if s.worker == nil {
		return "", ErrCaptureWorkerUnavailable
	}
	if err := s.worker.InvokeCleanNote(ctx, userID, noteID, mode); err != nil {
		return "", fmt.Errorf("failed to hand the note to the worker: %w", err)
	}
	obs.Log(ctx).Info("note clean handed to the worker",
		slog.String("note_id", noteID),
		slog.String("mode", string(mode)))
	obs.Count(ctx, "NoteCleanRequested", map[string]string{"Mode": string(mode), "Trigger": "user"})
	return mode, nil
}

// autoCleanAfterBodyWrite invokes the worker for a note whose body this
// request just changed, when the note asks for it. It never fails the caller:
// the body write is done and correct, and a hand-off that could not be made
// is a view that stays stale — which the note already says — not lost text.
func autoCleanAfterBodyWrite(ctx context.Context, worker Invoker, userID string, note model.NoteIndex) {
	if !note.AutoClean || !NoteIsActive(note) {
		return
	}
	if worker == nil {
		obs.Log(ctx).Warn("note asks for auto-clean but no worker is configured; the cleaned view stays stale",
			slog.String("note_id", note.ID))
		return
	}
	mode := EffectiveCleanMode(note)
	if err := worker.InvokeCleanNote(ctx, userID, note.ID, mode); err != nil {
		obs.Log(ctx).Error("could not hand the note to the worker for auto-clean; the cleaned view stays stale",
			slog.String("note_id", note.ID),
			slog.String("error", err.Error()))
		obs.Count(ctx, "NoteCleanInvokeFailures", map[string]string{"Trigger": "auto"})
		return
	}
	obs.Count(ctx, "NoteCleanRequested", map[string]string{"Mode": string(mode), "Trigger": "auto"})
}
