package service

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/vppillai/chintan/backend/internal/keys"
	"github.com/vppillai/chintan/backend/internal/match"
	"github.com/vppillai/chintan/backend/internal/model"
	"github.com/vppillai/chintan/backend/internal/obs"
	"github.com/vppillai/chintan/backend/internal/repository"
)

const ArchiveRetention = 30 * 24 * time.Hour

// maxNoteTitleLen bounds a stored title. It matches the OpenAPI document's
// maxLength for a note title, so a title the API accepts is a title that is
// stored whole. Two different limits for one field means a request the handler
// validated is quietly truncated by the service, which is data loss with a
// receipt.
//
// The routing prompt does not depend on this number: it bounds every rendered
// candidate field itself (routing.maxFieldLen), so a longer stored title cannot
// grow the prompt.
const maxNoteTitleLen = 200

var (
	ErrNoteArchived    = errors.New("note is archived")
	ErrNoteNotArchived = errors.New("note is not archived")
	ErrEmptyNoteTitle  = errors.New("note title is empty")
	// ErrPurgeIncomplete means part of a permanent delete failed. The note index
	// is deliberately left in place so the delete can be retried, because
	// reporting "purged" while audio survives in S3 is worse than reporting a
	// failure.
	ErrPurgeIncomplete = errors.New("note purge incomplete")
)

// maxMatchCandidates bounds how many notes note-matching will page through.
const maxMatchCandidates = 500

// sanitizeNoteTitle collapses a title to a single bounded line.
func sanitizeNoteTitle(title string) string {
	title = strings.Map(func(r rune) rune {
		if unicode.IsControl(r) {
			return ' '
		}
		return r
	}, title)
	title = strings.Join(strings.Fields(title), " ")
	if runes := []rune(title); len(runes) > maxNoteTitleLen {
		title = strings.TrimSpace(string(runes[:maxNoteTitleLen]))
	}
	return title
}

func NoteIsActive(n model.NoteIndex) bool {
	return strings.TrimSpace(n.DeletedAt) == ""
}

// maxTagLen bounds one tag. Tags are rendered into list filters and into the
// routing prompt, so an unbounded tag is a stored cost amplifier.
const maxTagLen = 40

// normalizeTags folds tags to a canonical form: trimmed, lowercased, collapsed
// whitespace, deduplicated, ordered. Without this "Roof", "roof " and "roof"
// are three tags in the index and one tag to the person who said them.
func normalizeTags(tags []string) []string {
	if len(tags) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(tags))
	out := make([]string, 0, len(tags))
	for _, raw := range tags {
		t := strings.ToLower(strings.Join(strings.Fields(raw), " "))
		if t == "" {
			continue
		}
		if runes := []rune(t); len(runes) > maxTagLen {
			t = strings.TrimSpace(string(runes[:maxTagLen]))
		}
		if _, dup := seen[t]; dup {
			continue
		}
		seen[t] = struct{}{}
		out = append(out, t)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return nil
	}
	return out
}

// NotesService handles note operations
type NotesService struct {
	store   repository.Store
	objects repository.Objects
	// worker is the hand-off for the clean-note task. Nil means POST
	// /v1/notes/{id}/clean answers 503 and auto-clean logs and skips.
	worker Invoker
	// now stamps clean requests (RequestClean); tests move it.
	now func() time.Time
}

// NoteUpdates represents partial updates to a note.
//
// ExpectedVersion is the version the client read. It is compared before
// anything is written, so a voice append landing while the editor is open
// surfaces as a conflict the client reconciles rather than one of the two
// writes vanishing. A nil ExpectedVersion skips the check and is for in-process
// callers only — every HTTP caller supplies one.
type NoteUpdates struct {
	Title    *string
	Aliases  *[]string
	Tags     *[]string
	Body     *string
	Verbatim *bool
	// Language is the transcription language for captures recorded into this
	// note: model.LanguageAuto, an ISO-639-1 code, or "" to fall back to the
	// tenant's default. Validated here, not only at the handler, because the
	// worker passes it straight to the provider.
	Language *string
	// AutoClean and CleanMode are the whole-note cleaned view's preferences
	// (note_clean.go). The view itself is not here: it is read-only from the
	// API and regenerated by the worker.
	AutoClean *bool
	CleanMode *model.NoteCleanMode
	// Kind is "" for a plain note or model.NoteKindChecklist. The body is not
	// converted here: the client rewrites it to the new kind's format in the
	// same PATCH, and a body it did not send is left as it is.
	Kind *string
	// Pinned puts the note in the Pinned group at the top of Home, or takes
	// it out. A new pin lands last among the pinned notes; the order within
	// the group is ReorderPins's.
	Pinned          *bool
	ExpectedVersion *int64
}

// ErrInvalidNoteKind rejects a kind that is not "" or checklist.
var ErrInvalidNoteKind = errors.New("kind must be note or checklist")

// Pin errors. The sentences reach the user as written.
var (
	// ErrPinLimit refuses the pin that would be one past model.MaxPinnedNotes.
	ErrPinLimit = errors.New("you can pin up to fifty notes")
	// ErrPinReorderInvalid refuses a reorder naming a note that is not the
	// caller's, not pinned, or named twice.
	ErrPinReorderInvalid = errors.New("every id must be one of your pinned notes")
	// ErrPinBatchSize refuses a reorder of no notes or of more than can be
	// pinned.
	ErrPinBatchSize = errors.New("ids must name between 1 and 50 notes")
)

// MatchResult represents the result of a note matching operation
type MatchResult struct {
	Candidates   []match.Candidate `json:"candidates"`
	AutoSelectID *string           `json:"auto_select_id,omitempty"`
}

// NewNotesService creates a new notes service
func NewNotesService(store repository.Store, objects repository.Objects) *NotesService {
	return &NotesService{
		store:   store,
		objects: objects,
		now:     time.Now,
	}
}

// WithClock replaces the clock RequestClean stamps requests with; tests use it
// to age a request past the worker's window.
func (s *NotesService) WithClock(now func() time.Time) *NotesService {
	s.now = now
	return s
}

// CreateNote creates a new note.
//
// The signature is what the worker's NoteCreator expects; CreateNoteWithTags is
// the fuller form the API uses.
func (s *NotesService) CreateNote(ctx context.Context, userID, title string, aliases []string) (model.NoteIndex, error) {
	return s.CreateNoteWithTags(ctx, userID, title, aliases, nil)
}

// CreateNoteWithTags creates a note carrying tags.
func (s *NotesService) CreateNoteWithTags(ctx context.Context, userID, title string, aliases, tags []string) (model.NoteIndex, error) {
	title = sanitizeNoteTitle(title)
	if title == "" {
		return model.NoteIndex{}, ErrEmptyNoteTitle
	}

	noteIDBytes := make([]byte, 8)
	if _, err := rand.Read(noteIDBytes); err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to generate note ID: %w", err)
	}
	// Same shape as a capture id: a fixed-width creation instant so ids sort
	// chronologically — the note index is keyed NOTE#<id>, so the id is what
	// decides list order — followed by random bytes. The clock alone is both
	// guessable from the creation time and collision-prone, and a collision
	// surfaces to the user as an unexplained 409 on a note they just made.
	noteID := fmt.Sprintf("note_%016x_%s",
		uint64(time.Now().UTC().UnixNano()), hex.EncodeToString(noteIDBytes))

	// Generate S3 keys
	markdownKey, err := keys.NoteMarkdown(userID, noteID)
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to generate markdown key: %w", err)
	}

	metaKey, err := keys.NoteMeta(userID, noteID)
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to generate meta key: %w", err)
	}

	if aliases == nil {
		aliases = []string{}
	}

	now := model.Now()
	note := model.NoteIndex{
		ID:            noteID,
		Title:         title,
		Aliases:       aliases,
		Tags:          normalizeTags(tags),
		Snippet:       "", // No content initially
		SearchText:    "",
		CreatedAt:     now,
		UpdatedAt:     now,
		S3MarkdownKey: markdownKey,
		S3MetaKey:     metaKey,
	}

	// Create initial empty markdown file
	err = s.objects.Put(ctx, markdownKey, []byte(""), "text/markdown")
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to create markdown file: %w", err)
	}

	// Create metadata file
	metaData := map[string]interface{}{
		"title":      title,
		"aliases":    aliases,
		"tags":       note.Tags,
		"created_at": note.CreatedAt,
		"updated_at": note.UpdatedAt,
	}
	metaBytes, _ := json.Marshal(metaData)
	err = s.objects.Put(ctx, metaKey, metaBytes, "application/json")
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to create meta file: %w", err)
	}

	// Save to store
	stored, err := s.store.PutNote(ctx, userID, note)
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to save note: %w", err)
	}

	return stored, nil
}

// ListNotes returns one page of active notes. Archived notes are excluded by
// the store, so the filtering is no longer paid for in Go.
func (s *NotesService) ListNotes(ctx context.Context, userID string, opts repository.ListOptions) (repository.Page[model.NoteIndex], error) {
	page, err := s.store.ListNotes(ctx, userID, opts)
	if err != nil {
		return page, err
	}
	noteListTruncated(ctx, page, "active")
	return page, nil
}

// DrainNotes is the whole of a shelf in one read (repository.Store.DrainNotes),
// for the callers that read every note anyway; it reports the ceiling the way
// ListNotes does.
func (s *NotesService) DrainNotes(ctx context.Context, userID string, opts repository.DrainOptions) ([]model.NoteIndex, error) {
	notes, truncated, err := s.store.DrainNotes(ctx, userID, opts)
	if err != nil {
		return nil, err
	}
	shelf := "active"
	if opts.Shelf == repository.NoteShelfArchived {
		shelf = "archived"
	}
	noteListTruncated(ctx, repository.Page[model.NoteIndex]{Truncated: truncated}, shelf)
	return notes, nil
}

// noteListTruncated is the one place a list that hit repository.MaxNotesDrained
// is reported. The store has no logger or metrics of its own, so it marks the
// page and this layer says so: once per list call at WARN, and a counter an
// operator can graph, because the symptom in the app — an old note touched
// today is not at the top of the library — does not point at its cause.
func noteListTruncated(ctx context.Context, page repository.Page[model.NoteIndex], shelf string) {
	if !page.Truncated {
		return
	}
	obs.Log(ctx).Warn("notes list hit the drain ceiling; the order is over an incomplete set",
		slog.String("shelf", shelf),
		slog.Int("ceiling", repository.MaxNotesDrained))
	// No dimension: the log line carries the shelf, and one identity is
	// enough for a counter whose healthy value is zero.
	obs.Count(ctx, "NotesListTruncated", nil)
}

// GetNote retrieves a specific note
func (s *NotesService) GetNote(ctx context.Context, userID, noteID string) (model.NoteIndex, error) {
	return s.store.GetNote(ctx, userID, noteID)
}

// NoteDetail is a note index plus markdown body for the editor.
type NoteDetail struct {
	model.NoteIndex
	Body string `json:"body"`
}

// GetNoteDetail retrieves a note and its markdown body from object storage.
func (s *NotesService) GetNoteDetail(ctx context.Context, userID, noteID string) (NoteDetail, error) {
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return NoteDetail{}, err
	}
	bodyBytes, err := s.objects.Get(ctx, note.S3MarkdownKey)
	if err != nil && !errors.Is(err, repository.ErrNotFound) {
		return NoteDetail{}, fmt.Errorf("failed to load note body: %w", err)
	}
	// The worker's append markers stay in the object and out of the editor;
	// UpdateNote puts them back. See note_markers.go.
	return NoteDetail{NoteIndex: note, Body: StripCaptureMarkers(string(bodyBytes))}, nil
}

// ErrAppendInProgress refuses a body write while the worker is putting a
// capture's paragraph into the same body. The handler answers it as a 409 in
// the version-conflict shape with `reason: append_in_progress` and a
// Retry-After, and the client repeats the same save unchanged once the append
// has landed — it must not re-read and rebase, because the version has moved
// for a body that has not yet.
var ErrAppendInProgress = errors.New("a recording is being added to this note")

// AppendInProgress reports whether n carries a stamp young enough that the
// append it announces may still be writing the body. A stamp older than the
// claim lease was left by a worker that died between stamping and writing;
// the lease is what lets that capture be retried, and the same bound lets the
// editor save again.
func AppendInProgress(n model.NoteIndex, now time.Time) bool {
	if n.AppendingCapture == "" || n.AppendingAt == "" {
		return false
	}
	at, err := model.ParseTime(n.AppendingAt)
	if err != nil {
		return false
	}
	return now.Sub(at) < repository.AppendClaimLease
}

// UpdateNote updates a note with partial changes.
//
// A body write has two concurrent writers to survive: another editor save,
// which the row's version catches, and the worker's append, which writes the
// body first and refreshes the row afterwards. The append is the hard one. Its
// body write moves the ETag and not the version, so a save whose row read
// preceded the append's version bump and whose body read followed the body
// write passed both checks and rewrote the body from text that predates the
// paragraph — carrying the marker forward, so nothing ever re-appended it.
// Three things close that (review 2026-09-05, S1), in this order below:
//
//   - The append stamps the row before it writes (Pipeline.append). A save
//     that finds the stamp is refused with ErrAppendInProgress, whatever its
//     version says, and the client repeats it once the stamp is gone.
//   - The body's ETag is read BEFORE the row, so the version is the later
//     witness. The stamp bumps the version, so a save whose row read saw the
//     old version read its ETag earlier still, before any body write the stamp
//     announced; the conditional PUT then loses to that write instead of
//     erasing it.
//   - The body write is conditional on the ETag it read, so any body write
//     between the two is a conflict, not a loss.
func (s *NotesService) UpdateNote(ctx context.Context, userID, noteID string, updates NoteUpdates) (model.NoteIndex, error) {
	// The body first, when there is one to write. The object key is derived
	// from the ids rather than read from the row, which is what lets the ETag
	// be read before the row is; a row naming a different key — nothing
	// writes one, but a row is data — falls back to reading after.
	//
	// The stored body is kept as well as its ETag: the client never saw the
	// worker's append markers (GetNoteDetail strips them), so they are put
	// back onto whatever it sends, or a save inside a capture's retry window
	// would erase the one fact that stops the retry appending twice.
	bodyETag := ""
	var storedBody []byte
	bodyReadFrom := ""
	if updates.Body != nil {
		key, err := keys.NoteMarkdown(userID, noteID)
		if err != nil {
			return model.NoteIndex{}, repository.ErrNotFound
		}
		storedBody, bodyETag, err = s.objects.GetWithETag(ctx, key)
		if err != nil && !errors.Is(err, repository.ErrNotFound) {
			return model.NoteIndex{}, fmt.Errorf("failed to read note body: %w", err)
		}
		bodyReadFrom = key
	}

	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return model.NoteIndex{}, err
	}

	// Check if note is archived
	if !NoteIsActive(note) {
		return model.NoteIndex{}, ErrNoteArchived
	}

	if updates.Body != nil {
		if bodyReadFrom != note.S3MarkdownKey {
			storedBody, bodyETag, err = s.objects.GetWithETag(ctx, note.S3MarkdownKey)
			if err != nil && !errors.Is(err, repository.ErrNotFound) {
				return model.NoteIndex{}, fmt.Errorf("failed to read note body: %w", err)
			}
		}
		// Before the version check, deliberately: the stamp bumped the version,
		// so every save that meets it is also a version conflict, and answered
		// as one it would be re-read and re-sent straight into the window it
		// has to wait out.
		if AppendInProgress(note, s.now()) {
			return note, ErrAppendInProgress
		}
		// A stamp past the lease was abandoned; this write is the row's next
		// and need not carry it.
		note.AppendingCapture, note.AppendingAt = "", ""
	}

	// The version the client read is checked before anything is written, which
	// rejects the common conflict cheaply. It cannot close the window on its
	// own: an append landing after this line and before the write below is
	// caught by the ETag, not by this.
	if updates.ExpectedVersion != nil && *updates.ExpectedVersion != note.Version {
		return note, repository.ErrVersionConflict
	}

	// Apply updates
	if updates.Title != nil {
		title := sanitizeNoteTitle(*updates.Title)
		if title == "" {
			return model.NoteIndex{}, ErrEmptyNoteTitle
		}
		note.Title = title
	}
	if updates.Aliases != nil {
		note.Aliases = *updates.Aliases
	}
	if updates.Tags != nil {
		note.Tags = normalizeTags(*updates.Tags)
	}
	if updates.Verbatim != nil {
		note.Verbatim = *updates.Verbatim
	}
	if updates.Language != nil {
		lang := strings.ToLower(strings.TrimSpace(*updates.Language))
		if lang != "" && !model.ValidLanguage(lang) {
			return model.NoteIndex{}, ErrInvalidLanguage
		}
		note.Language = lang
	}
	if updates.AutoClean != nil {
		note.AutoClean = *updates.AutoClean
	}
	if updates.Kind != nil {
		if !model.ValidNoteKind(*updates.Kind) {
			return model.NoteIndex{}, ErrInvalidNoteKind
		}
		note.Kind = *updates.Kind
	}
	if updates.CleanMode != nil {
		// Checked against the kind as this request leaves it, so a note can
		// become a checklist and take tasks in one PATCH.
		if err := CheckCleanMode(note, *updates.CleanMode); err != nil {
			return model.NoteIndex{}, err
		}
		note.CleanMode = *updates.CleanMode
	}
	if updates.Pinned != nil {
		switch {
		case *updates.Pinned && !note.Pinned():
			// A new pin lands last: its rank is one step past the highest in
			// use, from the same drain that counts the pins for the limit.
			// One drain of the partition, on a pin alone.
			pinned, nextRank, err := s.countPinned(ctx, userID)
			if err != nil {
				return model.NoteIndex{}, err
			}
			if pinned >= model.MaxPinnedNotes {
				return model.NoteIndex{}, ErrPinLimit
			}
			note.PinnedAt = model.FormatTime(s.now())
			note.PinRank = nextRank
		case !*updates.Pinned:
			note.PinnedAt, note.PinRank = "", 0
		}
	}

	// A pin is not an edit: it moves the note into the Pinned group, not
	// among the days, so only a change to what the note says or is bumps
	// updated_at and rewrites the meta object below. The version still moves,
	// through putCarryingStamp. Before this, an unpinned note re-filed under
	// Today and a pinned row read as edited just now (review 2026-09-24 R4-1).
	touched := updates.Title != nil || updates.Aliases != nil || updates.Tags != nil ||
		updates.Body != nil || updates.Verbatim != nil || updates.Language != nil ||
		updates.AutoClean != nil || updates.CleanMode != nil || updates.Kind != nil
	if touched {
		note.UpdatedAt = model.Now()
	}

	// Handle body update. The client sends its whole draft with a Details
	// change (language, kind, word-for-word, auto-clean), and a body that
	// reads the same as the stored one is not an edit: CarryCaptureMarkers
	// hands the stored bytes back for it, and nothing below is done — a
	// language change that marked the cleaned view stale had the Split up tab
	// offer a pointless Regenerate (review 2026-09-21 r4).
	if updates.Body != nil {
		body := CarryCaptureMarkers(string(storedBody), *updates.Body)
		if body != string(storedBody) {
			// Write to markdown file, conditional on the object still carrying the
			// ETag read above. An unconditional Put here destroys a voice append
			// that landed in the meantime and only then reports the conflict — the
			// client is told to re-read text that no longer exists anywhere.
			err = s.objects.PutIfMatch(ctx, note.S3MarkdownKey, []byte(body), "text/markdown", bodyETag)
			if errors.Is(err, repository.ErrPreconditionFailed) {
				// Somebody else wrote the body between the read and this write.
				// That is the same 409 the version check answers, and the client
				// reconciles it the same way.
				return note, repository.ErrVersionConflict
			}
			if err != nil {
				return model.NoteIndex{}, fmt.Errorf("failed to update markdown: %w", err)
			}

			// Update snippet (first ~500 chars) and the search text, which are the
			// two derivations of the body the index row carries.
			note.Snippet = generateSnippet(*updates.Body)
			note.SearchText = SearchText(*updates.Body)
			// The cleaned view was generated from the body that just changed —
			// unless the change was to adopt the view itself ("Use this list"): a
			// body equal to CleanedBody, trailing whitespace aside, IS the view,
			// so it is current whatever an earlier edit had marked it. Left
			// stale, the tab offered to regenerate a list identical to the note
			// (smoke 2026-09-21, finding 3).
			trim := func(s string) string { return strings.TrimRightFunc(s, unicode.IsSpace) }
			if note.CleanedBody != "" && trim(*updates.Body) == trim(note.CleanedBody) {
				note.CleanedStale = false
			} else {
				MarkCleanedStale(&note)
			}
		}
	}

	// Update metadata
	if touched {
		metaData := map[string]interface{}{
			"title":      note.Title,
			"aliases":    note.Aliases,
			"tags":       note.Tags,
			"verbatim":   note.Verbatim,
			"language":   note.Language,
			"kind":       note.Kind,
			"updated_at": note.UpdatedAt,
		}
		metaBytes, _ := json.Marshal(metaData)
		err = s.objects.Put(ctx, note.S3MetaKey, metaBytes, "application/json")
		if err != nil {
			return model.NoteIndex{}, fmt.Errorf("failed to update meta: %w", err)
		}
	}

	// Save to store. A version conflict here means somebody else wrote the note
	// between the read and this write; the caller reconciles rather than one of
	// the two edits vanishing.
	return s.putCarryingStamp(ctx, userID, note)
}

// countPinned is how many of the tenant's active notes are pinned, and the
// rank a new pin takes to land last: one step past the highest in use, which
// is count × PinRankStep while the ranks are compact and more once an unpin
// has left a gap. Count × step would then equal an existing rank, and the
// order's tie-break (the more recently pinned first) would put the new pin
// above that note instead of below it. Zero when nothing is pinned.
func (s *NotesService) countPinned(ctx context.Context, userID string) (count int, nextRank int64, err error) {
	notes, _, err := s.store.DrainNotes(ctx, userID, repository.DrainOptions{})
	if err != nil {
		return 0, 0, fmt.Errorf("failed to list notes: %w", err)
	}
	for _, n := range notes {
		if n.Pinned() {
			count++
			nextRank = max(nextRank, n.PinRank+model.PinRankStep)
		}
	}
	return count, nextRank, nil
}

// ReorderPins writes the listed notes' pin_rank as their position in ids,
// PinRankStep apart, and returns them in that order. Every id must name one
// of the caller's pinned, active notes, once; anything else refuses the whole
// request, since a partial reorder is not an order anyone asked for. One
// request per drag.
//
// Each note is read whole before it is written: a listed note carries no
// search_text or cleaned_body, and PutNote writes the row it is given, so a
// note put from a list projection would lose both. A note already at its
// rank is not rewritten, so a drag that moves one note writes one row.
func (s *NotesService) ReorderPins(ctx context.Context, userID string, ids []string) ([]model.NoteIndex, error) {
	if len(ids) == 0 || len(ids) > model.MaxPinnedNotes {
		return nil, ErrPinBatchSize
	}
	seen := make(map[string]bool, len(ids))
	notes := make([]model.NoteIndex, 0, len(ids))
	for _, id := range ids {
		if seen[id] {
			return nil, ErrPinReorderInvalid
		}
		seen[id] = true
		note, err := s.store.GetNote(ctx, userID, id)
		if errors.Is(err, repository.ErrNotFound) {
			return nil, ErrPinReorderInvalid
		}
		if err != nil {
			return nil, fmt.Errorf("failed to get note: %w", err)
		}
		if !note.Pinned() || !NoteIsActive(note) {
			return nil, ErrPinReorderInvalid
		}
		notes = append(notes, note)
	}
	out := make([]model.NoteIndex, 0, len(notes))
	for i, note := range notes {
		rank := int64(i) * model.PinRankStep
		if note.PinRank == rank {
			out = append(out, note)
			continue
		}
		note.PinRank = rank
		stored, err := s.putCarryingStamp(ctx, userID, note)
		if err != nil {
			return nil, err
		}
		out = append(out, stored)
	}
	return out, nil
}

// putCarryingStamp is PutNote for a write that did not touch the clean stamp.
//
// PutNote pins the stamp beside the version because a Clean tap
// (StampCleanRequest) moves the stamp without moving the version, and a
// whole-row write from a copy read before the tap would otherwise erase it. The
// pin cannot tell that stale copy from this caller, whose copy is only stale
// about the stamp: CleanedPanel fires saveNow() and regenerate() in one tick,
// so the tap routinely lands inside the save's read-modify-write window, and
// answered as a 409 the client would show a conflict prompt between two
// identical texts (the version did not move, so its rebase cannot absorb it).
// One re-read tells the two apart. The same version with a different stamp is
// the tap alone: the write goes again carrying it, and the worker finds its
// request intact. A moved version is somebody else's whole-row write, which is
// the conflict PutNote reported. On a conflict the row returned is the one now
// stored, so the handler can name the version the client has to reconcile
// against rather than 0.
func (s *NotesService) putCarryingStamp(ctx context.Context, userID string, note model.NoteIndex) (model.NoteIndex, error) {
	stored, err := s.store.PutNote(ctx, userID, note)
	if !errors.Is(err, repository.ErrVersionConflict) {
		return stored, err
	}
	fresh, readErr := s.store.GetNote(ctx, userID, note.ID)
	if readErr != nil {
		return note, err
	}
	if fresh.Version != note.Version {
		return fresh, err
	}
	note.CleanedRequestedAt, note.CleanedRequestedMode = fresh.CleanedRequestedAt, fresh.CleanedRequestedMode
	stored, err = s.store.PutNote(ctx, userID, note)
	if errors.Is(err, repository.ErrVersionConflict) {
		return fresh, err
	}
	return stored, err
}

// DeleteNote archives a note (soft delete)
func (s *NotesService) DeleteNote(ctx context.Context, userID, noteID string) error {
	_, err := s.ArchiveNote(ctx, userID, noteID)
	return err
}

// MatchNotes finds matching notes for a query (only searches active notes)
func (s *NotesService) MatchNotes(ctx context.Context, userID, query string) (MatchResult, error) {
	// Matching scores against every candidate, so it reads the whole active
	// set — once — rather than seeing whatever fitted in one page.
	notes, err := s.DrainNotes(ctx, userID, repository.DrainOptions{MaxItems: maxMatchCandidates})
	if err != nil {
		return MatchResult{}, err
	}

	// Rank all candidates first (following binding decision #1)
	candidates := match.Rank(query, notes, 0) // 0 means no limit, get all

	// Check for high confidence
	highConfidence := match.HighConfidence(candidates)

	// Limit response to reasonable number for UI
	if len(candidates) > 10 {
		candidates = candidates[:10]
	}

	result := MatchResult{
		Candidates: candidates,
	}

	// Set auto_select_id only for high confidence matches
	if highConfidence && len(candidates) > 0 {
		result.AutoSelectID = &candidates[0].NoteID
	}

	return result, nil
}

// generateSnippet creates a snippet from a note body.
//
// The cut is by rune, not byte. A byte slice cuts multi-byte runes in half and
// writes invalid UTF-8 into DynamoDB and into the routing prompt.
//
// The worker's append markers are removed first: the snippet is shown in the
// notes list and handed to the router as a summary of the note, and neither
// wants an HTML comment in it.
func generateSnippet(body string) string {
	const maxRunes = 500
	body = StripCaptureMarkers(body)
	runes := []rune(body)
	if len(runes) <= maxRunes {
		return body
	}
	return string(runes[:maxRunes]) + "..."
}

// ArchiveNote archives a note (soft delete with retention period)
func (s *NotesService) ArchiveNote(ctx context.Context, userID, noteID string) (model.NoteIndex, error) {
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return model.NoteIndex{}, err
	}

	// If already archived, return as-is (idempotent)
	if !NoteIsActive(note) {
		return note, nil
	}

	// Set archive timestamps. PurgeAfterEpoch is the deadline the archived list
	// filters on and the weekly expiry sweep (internal/purge) collects on; the
	// store derives the DynamoDB TTL backstop from it. Nothing sweeps on read.
	now := time.Now().UTC()
	purgeAt := now.Add(ArchiveRetention)
	note.DeletedAt = model.FormatTime(now)
	note.PurgeAfter = model.FormatTime(purgeAt)
	note.PurgeAfterEpoch = purgeAt.Unix()
	// The archive is never pinned, and a restore comes back unpinned: the
	// pin was a place on Home, and the note has left Home.
	note.PinnedAt, note.PinRank = "", 0

	return s.putCarryingStamp(ctx, userID, note)
}

// RestoreNote restores an archived note to active status
func (s *NotesService) RestoreNote(ctx context.Context, userID, noteID string) (model.NoteIndex, error) {
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return model.NoteIndex{}, err
	}

	// If already active, return as-is (idempotent)
	if NoteIsActive(note) {
		return note, nil
	}

	// Clear archive fields, including the TTL, so the table stops counting down.
	note.DeletedAt = ""
	note.PurgeAfter = ""
	note.PurgeAfterEpoch = 0

	return s.putCarryingStamp(ctx, userID, note)
}

// ListArchivedNotes returns one page of archived notes that have not passed
// their purge deadline. Expiry itself belongs to DynamoDB TTL; the filter only
// keeps an item the table has not collected yet out of the UI.
func (s *NotesService) ListArchivedNotes(ctx context.Context, userID string, opts repository.ListOptions) (repository.Page[model.NoteIndex], error) {
	page, err := s.store.ListArchivedNotes(ctx, userID, opts)
	if err != nil {
		return page, err
	}
	noteListTruncated(ctx, page, "archived")
	return page, nil
}

// PermanentlyDeleteNote permanently deletes an archived note and all its captures
func (s *NotesService) PermanentlyDeleteNote(ctx context.Context, userID, noteID string) error {
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return err
	}

	// Must be archived first
	if NoteIsActive(note) {
		return ErrNoteNotArchived
	}

	return s.hardDeleteNote(ctx, userID, noteID, note, nil)
}

// hardDeleteNote removes a note's captures, its objects, and finally its index.
//
// It fails loudly. Logging a cascade failure and deleting the index anyway
// permanently orphans audio the UI has reported as purged. Here the index
// survives any failure, so the note stays visible as archived and the delete
// can be retried.
func (s *NotesService) hardDeleteNote(ctx context.Context, userID, noteID string, note model.NoteIndex, legacy *unindexedCaptures) error {
	if err := s.purgeNoteArtifacts(ctx, userID, noteID, note, legacy); err != nil {
		return err
	}
	return s.store.DeleteNote(ctx, userID, noteID)
}

// unindexedCaptures is the tenant's captures the note index cannot see (see
// PurgeNoteArtifacts), read once and shared by every note of one batch. A nil
// *unindexedCaptures means "read them now", which a single delete does.
type unindexedCaptures struct {
	captures []model.CaptureIndex
}

// PurgeNoteArtifacts unlinks everything a note owns apart from its own index
// row: every capture filed against it, every S3 object those captures name, and
// the note's own body and metadata.
//
// It is separate from hardDeleteNote because the same cascade has to run from
// two places that disagree about whether the index row still exists. A user
// asking to delete forever arrives through hardDeleteNote, which removes the row
// last so a failed cascade leaves the note visible and retryable. DynamoDB TTL
// arrives through internal/purge, by which point the row is already gone and
// there is nothing left to delete — only the objects it named, which is exactly
// this. Before that handler existed, TTL removed the index row and left the
// audio, raw transcript, routed transcript, cleaned text, segments and peaks in
// the bucket, billed and unreachable, with `chintanctl reconcile` as the only
// way to find them.
//
// Every failure is returned rather than logged, so a caller that must not
// declare a purge complete can tell that it is not.
func (s *NotesService) PurgeNoteArtifacts(ctx context.Context, userID, noteID string, note model.NoteIndex) error {
	return s.purgeNoteArtifacts(ctx, userID, noteID, note, nil)
}

// purgeNoteArtifacts is PurgeNoteArtifacts with the base-table read of the
// unindexed captures supplied by the caller when it has already made it. A
// batch purge of a hundred notes made that read — the tenant's whole capture
// partition — a hundred times, once per note, and could not finish inside the
// API function's 29 seconds (review 2026-09-05, S6).
func (s *NotesService) purgeNoteArtifacts(ctx context.Context, userID, noteID string, note model.NoteIndex, legacy *unindexedCaptures) error {
	// Every page, not just the first: a truncated list is how "delete forever"
	// leaves orphans behind.
	captures, err := repository.DrainPages(ctx, 0, func(ctx context.Context, opts repository.ListOptions) (repository.Page[model.CaptureIndex], error) {
		return s.store.ListCapturesByNote(ctx, userID, noteID, opts)
	})
	if err != nil {
		return fmt.Errorf("%w: list captures: %w", ErrPurgeIncomplete, err)
	}

	// And the captures the index cannot see. A row written before the index
	// keys were promoted (August 2026) is not in GSI1 at all, so the query
	// above is complete only for rows the current code wrote. In production
	// this is how "delete forever" removed every note and left thirteen filed
	// captures pointing at them, each still answering GET /v1/captures as a
	// receipt. The base-table read is the honest fix rather than promoting
	// the keys on read: it finds the rows now, for this purge, instead of
	// repairing the index for a later one that may never come — and a purge
	// is rare enough to afford one partition read per note.
	seen := make(map[string]bool, len(captures))
	for _, c := range captures {
		seen[c.ID] = true
	}
	if legacy == nil {
		unindexed, err := s.store.ListUnindexedCaptures(ctx, userID)
		if err != nil {
			return fmt.Errorf("%w: list unindexed captures: %w", ErrPurgeIncomplete, err)
		}
		legacy = &unindexedCaptures{captures: unindexed}
	}
	for _, c := range legacy.captures {
		if c.NoteID == noteID && !seen[c.ID] {
			captures = append(captures, c)
		}
	}

	for _, c := range captures {
		// Every object the capture may own, including a peaks key the row no
		// longer records; see captureObjectKeys.
		for _, key := range captureObjectKeys(userID, c) {
			if err := s.deleteObject(ctx, key); err != nil {
				return fmt.Errorf("%w: capture %s object: %w", ErrPurgeIncomplete, c.ID, err)
			}
		}
		if err := s.store.DeleteCapture(ctx, userID, c.ID); err != nil && !errors.Is(err, repository.ErrNotFound) {
			return fmt.Errorf("%w: capture %s index: %w", ErrPurgeIncomplete, c.ID, err)
		}
	}

	if err := s.deleteObject(ctx, note.S3MarkdownKey); err != nil {
		return fmt.Errorf("%w: note body: %w", ErrPurgeIncomplete, err)
	}
	if err := s.deleteObject(ctx, note.S3MetaKey); err != nil {
		return fmt.Errorf("%w: note meta: %w", ErrPurgeIncomplete, err)
	}

	return nil
}

// deleteObject removes a key, treating "already gone" as success so a retried
// purge can make progress.
func (s *NotesService) deleteObject(ctx context.Context, key string) error {
	return deleteObjectIfPresent(ctx, s.objects, key)
}

// MaxPurgeBatch bounds one batch purge by count; purgeTimeBudget bounds it by
// time, which is the bound that actually holds.
//
// A purge is not one delete but a cascade over every capture of every note
// named, and each capture unlinks six objects. A hundred notes with a handful
// of captures each is already several hundred S3 calls, and whether that fits
// the API Lambda's 29 seconds depends on S3's mood, not on the count: the
// owner's small batch took 5.5 s. So the count bounds the request body and the
// clock bounds the work — a batch that runs out of time stops and reports the
// notes it did not reach as failed, "not attempted", for the client to send
// again, rather than running into the gateway's 504 and leaving the client's
// idempotency key claimed for the lease. "Clear all" is the client listing its
// archive and sending it in batches, which is also why there is deliberately
// no "purge everything" switch — a flag like that is one malformed request
// away from emptying an account, and nothing here needs it.
const MaxPurgeBatch = 100

// purgeTimeBudget is how long one PurgeNotes call works before it stops
// starting notes. The API function's Timeout is 29 s and the gateway's
// ceiling 30 s; twenty seconds leaves the note in progress time to finish and
// the response time to be written.
const purgeTimeBudget = 20 * time.Second

// purgeDeadlineMargin is kept back from the request's own deadline when that
// is nearer than the budget, so the response is written before the deadline
// rather than the work running into it.
const purgeDeadlineMargin = 4 * time.Second

// The fixed sentences a note the batch did not reach carries. They reach the
// user, and they ask for exactly one thing.
const (
	purgeNotAttemptedDetail = "not attempted: this batch ran out of time; send the remaining notes again"
	purgeLegacyListFailed   = "the account's recordings could not be listed, so nothing was deleted; try again"
)

// Purge outcomes. They are stable strings because a client branches on them.
const (
	// PurgeStatusPurged means the note and everything it owned are gone.
	PurgeStatusPurged = "purged"
	// PurgeStatusNotFound means there was no such note. Replaying a batch that
	// already succeeded reports this, which is what makes a retry safe.
	PurgeStatusNotFound = "not_found"
	// PurgeStatusFailed means the note is still there. Either it was not
	// archived — refusing that is what stops a stale client turning "clear my
	// archive" into "delete my notes" — or part of its cascade failed, in which
	// case the index row is deliberately left so the delete can be retried.
	PurgeStatusFailed = "failed"
)

// PurgeResult is one note's outcome. Detail is written for a person and never
// carries infrastructure text.
type PurgeResult struct {
	NoteID string `json:"note_id"`
	Status string `json:"status"`
	Detail string `json:"detail,omitempty"`
}

// ErrPurgeBatchTooLarge rejects a batch above MaxPurgeBatch.
var ErrPurgeBatchTooLarge = errors.New("too many notes in one purge")

// ErrPurgeBatchEmpty rejects a batch naming nothing.
var ErrPurgeBatchEmpty = errors.New("no notes named")

// PurgeNotes permanently deletes several archived notes and reports each
// outcome separately.
//
// It is not all-or-nothing, and it does not pretend to be. There is no
// transaction spanning DynamoDB and S3, so a batch that reported a single
// success or failure would be lying about the notes on the other side of the
// first problem; the client is told what happened to each and can show what
// survived.
//
// One note's failure never stops the batch. The alternative — abandoning the
// rest — turns a single unlinkable object into a purge the user has to retry
// from the beginning, repeatedly, with a different note failing each time.
func (s *NotesService) PurgeNotes(ctx context.Context, userID string, noteIDs []string) ([]PurgeResult, error) {
	switch {
	case len(noteIDs) == 0:
		return nil, ErrPurgeBatchEmpty
	case len(noteIDs) > MaxPurgeBatch:
		return nil, ErrPurgeBatchTooLarge
	}

	results := make([]PurgeResult, 0, len(noteIDs))
	// A batch may name the same note twice — a client assembling "clear all"
	// from overlapping pages will. Purging it once and reporting the second as
	// already gone is honest; running the cascade twice is wasted work.
	seen := make(map[string]bool, len(noteIDs))

	// The clock the batch works against. The request's own deadline wins when
	// it is the nearer, less the margin the response needs.
	budget := purgeTimeBudget
	if d, ok := ctx.Deadline(); ok {
		if remaining := time.Until(d) - purgeDeadlineMargin; remaining < budget {
			budget = remaining
		}
	}
	stopAt := s.now().Add(budget)

	// The base-table read of the captures the index cannot see, once for the
	// whole batch rather than once per note.
	unindexed, err := s.store.ListUnindexedCaptures(ctx, userID)
	if err != nil {
		obs.Log(ctx).Error("batch purge could not list the tenant's unindexed captures; nothing was deleted",
			slog.Int("notes", len(noteIDs)), slog.String("error", err.Error()))
		for _, noteID := range noteIDs {
			results = append(results, PurgeResult{NoteID: noteID, Status: PurgeStatusFailed, Detail: purgeLegacyListFailed})
		}
		return results, nil
	}
	legacy := &unindexedCaptures{captures: unindexed}

	notAttempted := 0
	for _, noteID := range noteIDs {
		if seen[noteID] {
			results = append(results, PurgeResult{
				NoteID: noteID, Status: PurgeStatusNotFound,
				Detail: "named more than once in this batch",
			})
			continue
		}
		seen[noteID] = true
		if !s.now().Before(stopAt) {
			notAttempted++
			results = append(results, PurgeResult{NoteID: noteID, Status: PurgeStatusFailed, Detail: purgeNotAttemptedDetail})
			continue
		}
		results = append(results, s.purgeOne(ctx, userID, noteID, legacy))
	}
	if notAttempted > 0 {
		obs.Log(ctx).Warn("batch purge ran out of time; the remaining notes were reported for retry",
			slog.Int("notes", len(noteIDs)), slog.Int("not_attempted", notAttempted),
			slog.Int64("budget_ms", budget.Milliseconds()))
		obs.Count(ctx, "NotePurgeBatchOutOfTime", nil)
	}
	return results, nil
}

// purgeOne is PermanentlyDeleteNote with its errors turned into an outcome
// rather than a failure of the whole request.
func (s *NotesService) purgeOne(ctx context.Context, userID, noteID string, legacy *unindexedCaptures) PurgeResult {
	note, err := s.store.GetNote(ctx, userID, noteID)
	switch {
	case errors.Is(err, repository.ErrNotFound):
		// Already gone, or never existed, or belongs to another tenant — the
		// store cannot tell those apart from here and must not, since the
		// answer would confirm another tenant's identifier.
		return PurgeResult{NoteID: noteID, Status: PurgeStatusNotFound, Detail: "no such note"}
	case err != nil:
		return PurgeResult{
			NoteID: noteID, Status: PurgeStatusFailed,
			Detail: "the note could not be read; nothing was deleted",
		}
	}

	if NoteIsActive(note) {
		// The refusal that matters. A client working from a stale archive
		// listing would otherwise turn "clear my archive" into "delete the
		// notes I am still using", and a purge is not reversible.
		return PurgeResult{
			NoteID: noteID, Status: PurgeStatusFailed,
			Detail: "this note is not archived, so it was not deleted; archive it first",
		}
	}

	if err := s.hardDeleteNote(ctx, userID, noteID, note, legacy); err != nil {
		// The index row survives a failed cascade by design, so the note is
		// still listed as archived and the purge can be retried. Reporting
		// success here would leave audio in the bucket that the UI had already
		// said was deleted.
		//
		// The detail is fixed text: the underlying error carries bucket and
		// table names, and it is logged rather than returned.
		obs.Log(ctx).Error("batch purge could not finish a note",
			slog.String("note_id", noteID), slog.String("error", err.Error()))
		return PurgeResult{
			NoteID: noteID, Status: PurgeStatusFailed,
			Detail: "some of this note's files could not be removed; it is still here and can be deleted again",
		}
	}

	return PurgeResult{NoteID: noteID, Status: PurgeStatusPurged}
}
