package service

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/vppillai/chintan/backend/internal/keys"
	"github.com/vppillai/chintan/backend/internal/match"
	"github.com/vppillai/chintan/backend/internal/model"
	"github.com/vppillai/chintan/backend/internal/obs"
	"github.com/vppillai/chintan/backend/internal/repository"
)

// maxNoteTitleLen bounds a stored title. It matches the OpenAPI document's
// maxLength for a note title, so a title the API accepts is a title that is
// stored whole. Two different limits for one field means a request the handler
// validated is quietly truncated by the service, which is data loss with a
// receipt.
//
// The routing prompt does not depend on this number: it bounds every rendered
// candidate field itself (routing.maxFieldLen), so a longer stored title cannot
// grow the prompt.
const maxNoteTitleLen = 200

var (
	ErrNoteArchived    = errors.New("note is archived")
	ErrNoteNotArchived = errors.New("note is not archived")
	ErrEmptyNoteTitle  = errors.New("note title is empty")
)

// maxMatchCandidates bounds how many notes note-matching will page through.
const maxMatchCandidates = 500

// sanitizeNoteTitle collapses a title to a single bounded line.
func sanitizeNoteTitle(title string) string {
	title = strings.Map(func(r rune) rune {
		if unicode.IsControl(r) {
			return ' '
		}
		return r
	}, title)
	title = strings.Join(strings.Fields(title), " ")
	if runes := []rune(title); len(runes) > maxNoteTitleLen {
		title = strings.TrimSpace(string(runes[:maxNoteTitleLen]))
	}
	return title
}

func NoteIsActive(n model.NoteIndex) bool {
	return strings.TrimSpace(n.DeletedAt) == ""
}

// maxTagLen bounds one tag. Tags are rendered into list filters, search and,
// since 2026-09-27, the routing prompt's candidate lines beside the aliases
// (routing.Candidate.Tags), so an unbounded tag is a stored cost amplifier;
// the prompt bounds each rendered field again (routing.maxFieldLen).
const maxTagLen = 40

// normalizeTags folds tags to a canonical form: trimmed, lowercased, collapsed
// whitespace, deduplicated, ordered. Without this "Roof", "roof " and "roof"
// are three tags in the index and one tag to the person who said them.
func normalizeTags(tags []string) []string {
	if len(tags) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(tags))
	out := make([]string, 0, len(tags))
	for _, raw := range tags {
		t := strings.ToLower(strings.Join(strings.Fields(raw), " "))
		if t == "" {
			continue
		}
		if runes := []rune(t); len(runes) > maxTagLen {
			t = strings.TrimSpace(string(runes[:maxTagLen]))
		}
		if _, dup := seen[t]; dup {
			continue
		}
		seen[t] = struct{}{}
		out = append(out, t)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return nil
	}
	return out
}

// NotesService handles note operations
type NotesService struct {
	store   repository.Store
	objects repository.Objects
	// worker is the hand-off for the clean-note task. Nil means POST
	// /v1/notes/{id}/clean answers 503 and auto-clean logs and skips.
	worker Invoker
	// now stamps clean requests (RequestClean); tests move it.
	now func() time.Time
}

// NoteUpdates represents partial updates to a note.
//
// ExpectedVersion is the version the client read. It is compared before
// anything is written, so a voice append landing while the editor is open
// surfaces as a conflict the client reconciles rather than one of the two
// writes vanishing. A nil ExpectedVersion skips the check and is for in-process
// callers only — every HTTP caller supplies one.
type NoteUpdates struct {
	Title    *string
	Aliases  *[]string
	Tags     *[]string
	Body     *string
	Verbatim *bool
	// Language is the transcription language for captures recorded into this
	// note: model.LanguageAuto, an ISO-639-1 code, or "" to fall back to the
	// tenant's default. Validated here, not only at the handler, because the
	// worker passes it straight to the provider.
	Language *string
	// AutoClean and CleanMode are the whole-note cleaned view's preferences
	// (note_clean.go). The view itself is not here: it is read-only from the
	// API and regenerated by the worker.
	AutoClean *bool
	CleanMode *model.NoteCleanMode
	// Kind is "" for a plain note or model.NoteKindChecklist. The body is not
	// converted here: the client rewrites it to the new kind's format in the
	// same PATCH, and a body it did not send is left as it is.
	Kind *string
	// Pinned puts the note in the Pinned group at the top of Home, or takes
	// it out. A new pin lands last among the pinned notes; the order within
	// the group is ReorderPins's.
	Pinned          *bool
	ExpectedVersion *int64
}

// ErrInvalidNoteKind rejects a kind that is not "" or checklist.
var ErrInvalidNoteKind = errors.New("kind must be note or checklist")

// MatchResult represents the result of a note matching operation
type MatchResult struct {
	Candidates   []match.Candidate `json:"candidates"`
	AutoSelectID *string           `json:"auto_select_id,omitempty"`
}

// NewNotesService creates a new notes service
func NewNotesService(store repository.Store, objects repository.Objects) *NotesService {
	return &NotesService{
		store:   store,
		objects: objects,
		now:     time.Now,
	}
}

// WithClock replaces the clock the service stamps rows with (updated_at,
// pinned_at, clean requests). Test seam: tests use it to age a request past
// the worker's window, or to move an update a second past its create.
func (s *NotesService) WithClock(now func() time.Time) *NotesService {
	s.now = now
	return s
}

// CreateNote creates a new note.
//
// The signature is what the capture service's NoteCreator expects;
// CreateNoteWithTags is the fuller form the API uses, and CreateNoteOnce the
// worker's.
func (s *NotesService) CreateNote(ctx context.Context, userID, title string, aliases []string) (model.NoteIndex, error) {
	return s.CreateNoteWithTags(ctx, userID, title, aliases, nil)
}

// CreateNoteWithTags creates a note carrying tags.
func (s *NotesService) CreateNoteWithTags(ctx context.Context, userID, title string, aliases, tags []string) (model.NoteIndex, error) {
	title = sanitizeNoteTitle(title)
	if title == "" {
		return model.NoteIndex{}, ErrEmptyNoteTitle
	}

	noteIDBytes := make([]byte, 8)
	if _, err := rand.Read(noteIDBytes); err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to generate note ID: %w", err)
	}
	// Same shape as a capture id: a fixed-width creation instant so ids sort
	// chronologically — the note index is keyed NOTE#<id>, so the id is what
	// decides list order — followed by random bytes. The clock alone is both
	// guessable from the creation time and collision-prone, and a collision
	// surfaces to the user as an unexplained 409 on a note they just made.
	noteID := fmt.Sprintf("note_%016x_%s",
		uint64(time.Now().UTC().UnixNano()), hex.EncodeToString(noteIDBytes))
	return s.createNote(ctx, userID, model.NoteIndex{ID: noteID, Title: title, Aliases: aliases, Tags: normalizeTags(tags)})
}

// CreateNoteOnce creates spec — its ID, Title, Kind and Language — unless a
// note with that id already exists, and then returns that note as it is. It
// is the worker's create for a routed capture, whose id is derived from the
// capture's (pipeline.routedNoteID): a retry after a crash finds the note the
// first attempt made instead of making a second, and kind and language are
// on the row from its one write. The existing note's body is never
// rewritten, since another recording may already be in it.
func (s *NotesService) CreateNoteOnce(ctx context.Context, userID string, spec model.NoteIndex) (model.NoteIndex, error) {
	existing, err := s.store.GetNote(ctx, userID, spec.ID)
	if err == nil {
		return existing, nil
	}
	if !errors.Is(err, repository.ErrNotFound) {
		return model.NoteIndex{}, fmt.Errorf("failed to read note: %w", err)
	}
	spec.Title = sanitizeNoteTitle(spec.Title)
	if spec.Title == "" {
		return model.NoteIndex{}, ErrEmptyNoteTitle
	}
	note, err := s.createNote(ctx, userID, model.NoteIndex{ID: spec.ID, Title: spec.Title, Tags: normalizeTags(nil), Kind: spec.Kind, Language: spec.Language})
	if errors.Is(err, repository.ErrVersionConflict) {
		// Two deliveries of one capture raced past the read; the row is
		// written with version 0 expected, so exactly one of them made it.
		return s.store.GetNote(ctx, userID, spec.ID)
	}
	return note, err
}

// createNote writes the empty body, the meta mirror and the row for note,
// whose ID and Title are set. The row is a version-0 PutNote, which fails
// with ErrVersionConflict when the id is taken.
func (s *NotesService) createNote(ctx context.Context, userID string, note model.NoteIndex) (model.NoteIndex, error) {
	noteID, title := note.ID, note.Title
	aliases := note.Aliases

	// Generate S3 keys
	markdownKey, err := keys.NoteMarkdown(userID, noteID)
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to generate markdown key: %w", err)
	}

	metaKey, err := keys.NoteMeta(userID, noteID)
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to generate meta key: %w", err)
	}

	if aliases == nil {
		aliases = []string{}
	}

	now := model.FormatTime(s.now())
	note.Aliases = aliases
	note.CreatedAt = now
	note.UpdatedAt = now
	note.S3MarkdownKey = markdownKey
	note.S3MetaKey = metaKey

	// Create initial empty markdown file
	err = s.objects.Put(ctx, markdownKey, []byte(""), "text/markdown")
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to create markdown file: %w", err)
	}

	// Create metadata file
	metaData := map[string]interface{}{
		"title":      title,
		"aliases":    aliases,
		"tags":       note.Tags,
		"created_at": note.CreatedAt,
		"updated_at": note.UpdatedAt,
	}
	metaBytes, _ := json.Marshal(metaData)
	err = s.objects.Put(ctx, metaKey, metaBytes, "application/json")
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to create meta file: %w", err)
	}

	// Save to store
	stored, err := s.store.PutNote(ctx, userID, note)
	if err != nil {
		return model.NoteIndex{}, fmt.Errorf("failed to save note: %w", err)
	}

	return stored, nil
}

// ListNotes returns one page of active notes. Archived notes are excluded by
// the store, so the filtering is no longer paid for in Go.
func (s *NotesService) ListNotes(ctx context.Context, userID string, opts repository.ListOptions) (repository.Page[model.NoteIndex], error) {
	page, err := s.store.ListNotes(ctx, userID, opts)
	if err != nil {
		return page, err
	}
	noteListTruncated(ctx, page, "active")
	return page, nil
}

// DrainNotes is the whole of a shelf in one read (repository.Store.DrainNotes),
// for the callers that read every note anyway; it reports the ceiling the way
// ListNotes does.
func (s *NotesService) DrainNotes(ctx context.Context, userID string, opts repository.DrainOptions) ([]model.NoteIndex, error) {
	notes, truncated, err := s.store.DrainNotes(ctx, userID, opts)
	if err != nil {
		return nil, err
	}
	shelf := "active"
	if opts.Shelf == repository.NoteShelfArchived {
		shelf = "archived"
	}
	noteListTruncated(ctx, repository.Page[model.NoteIndex]{Truncated: truncated}, shelf)
	return notes, nil
}

// noteListTruncated is the one place a list that hit repository.MaxNotesDrained
// is reported. The store has no logger or metrics of its own, so it marks the
// page and this layer says so: once per list call at WARN, and a counter an
// operator can graph, because the symptom in the app — an old note touched
// today is not at the top of the library — does not point at its cause.
func noteListTruncated(ctx context.Context, page repository.Page[model.NoteIndex], shelf string) {
	if !page.Truncated {
		return
	}
	obs.Log(ctx).Warn("notes list hit the drain ceiling; the order is over an incomplete set",
		slog.String("shelf", shelf),
		slog.Int("ceiling", repository.MaxNotesDrained))
	// No dimension: the log line carries the shelf, and one identity is
	// enough for a counter whose healthy value is zero.
	obs.Count(ctx, "NotesListTruncated", nil)
}

// ListArchivedNotes returns one page of archived notes that have not passed
// their purge deadline. Expiry itself belongs to DynamoDB TTL; the filter only
// keeps an item the table has not collected yet out of the UI.
func (s *NotesService) ListArchivedNotes(ctx context.Context, userID string, opts repository.ListOptions) (repository.Page[model.NoteIndex], error) {
	page, err := s.store.ListArchivedNotes(ctx, userID, opts)
	if err != nil {
		return page, err
	}
	noteListTruncated(ctx, page, "archived")
	return page, nil
}

// GetNote retrieves a specific note
func (s *NotesService) GetNote(ctx context.Context, userID, noteID string) (model.NoteIndex, error) {
	return s.store.GetNote(ctx, userID, noteID)
}

// NoteDetail is a note index plus markdown body for the editor.
type NoteDetail struct {
	model.NoteIndex
	Body string `json:"body"`
}

// GetNoteDetail retrieves a note and its markdown body from object storage.
func (s *NotesService) GetNoteDetail(ctx context.Context, userID, noteID string) (NoteDetail, error) {
	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return NoteDetail{}, err
	}
	bodyBytes, err := s.objects.Get(ctx, note.S3MarkdownKey)
	if err != nil && !errors.Is(err, repository.ErrNotFound) {
		return NoteDetail{}, fmt.Errorf("failed to load note body: %w", err)
	}
	// The worker's append markers stay in the object and out of the editor;
	// UpdateNote puts them back. See note_markers.go.
	return NoteDetail{NoteIndex: note, Body: StripCaptureMarkers(string(bodyBytes))}, nil
}

// MatchNotes finds matching notes for a query (only searches active notes)
func (s *NotesService) MatchNotes(ctx context.Context, userID, query string) (MatchResult, error) {
	// Matching scores against every candidate, so it reads the whole active
	// set — once — rather than seeing whatever fitted in one page.
	notes, err := s.DrainNotes(ctx, userID, repository.DrainOptions{MaxItems: maxMatchCandidates})
	if err != nil {
		return MatchResult{}, err
	}

	// Rank all candidates first (following binding decision #1)
	candidates := match.Rank(query, notes, 0) // 0 means no limit, get all

	// Check for high confidence
	highConfidence := match.HighConfidence(candidates)

	// Limit response to reasonable number for UI
	if len(candidates) > 10 {
		candidates = candidates[:10]
	}

	result := MatchResult{
		Candidates: candidates,
	}

	// Set auto_select_id only for high confidence matches
	if highConfidence && len(candidates) > 0 {
		result.AutoSelectID = &candidates[0].NoteID
	}

	return result, nil
}

// Snippet derives the list snippet from a note body.
//
// The cut is by rune, not byte. A byte slice cuts multi-byte runes in half and
// writes invalid UTF-8 into DynamoDB and into the routing prompt.
//
// The worker's append markers are removed first: the snippet is shown in the
// notes list and handed to the router as a summary of the note, and neither
// wants an HTML comment in it.
func Snippet(body string) string {
	const maxRunes = 500
	body = StripCaptureMarkers(body)
	runes := []rune(body)
	if len(runes) <= maxRunes {
		return body
	}
	return string(runes[:maxRunes]) + "..."
}

// ErrAppendInProgress refuses a body write while the worker is putting a
// capture's paragraph into the same body. The handler answers it as a 409 in
// the version-conflict shape with `reason: append_in_progress` and a
// Retry-After, and the client repeats the same save unchanged once the append
// has landed — it must not re-read and rebase, because the version has moved
// for a body that has not yet.
var ErrAppendInProgress = errors.New("a recording is being added to this note")

// AppendInProgress reports whether n carries a stamp young enough that the
// append it announces may still be writing the body. A stamp older than the
// claim lease was left by a worker that died between stamping and writing;
// the lease is what lets that capture be retried, and the same bound lets the
// editor save again.
func AppendInProgress(n model.NoteIndex, now time.Time) bool {
	if n.AppendingCapture == "" || n.AppendingAt == "" {
		return false
	}
	at, err := model.ParseTime(n.AppendingAt)
	if err != nil {
		return false
	}
	return now.Sub(at) < repository.AppendClaimLease
}

// UpdateNote updates a note with partial changes.
//
// A body write has two concurrent writers to survive: another editor save,
// which the row's version catches, and the worker's append, which writes the
// body first and refreshes the row afterwards. The append is the hard one. Its
// body write moves the ETag and not the version, so a save whose row read
// preceded the append's version bump and whose body read followed the body
// write passed both checks and rewrote the body from text that predates the
// paragraph — carrying the marker forward, so nothing ever re-appended it.
// Three things close that (review 2026-09-05, S1), in this order below:
//
//   - The append stamps the row before it writes (Pipeline.append). A save
//     that finds the stamp is refused with ErrAppendInProgress, whatever its
//     version says, and the client repeats it once the stamp is gone.
//   - The body's ETag is read BEFORE the row, so the version is the later
//     witness. The stamp bumps the version, so a save whose row read saw the
//     old version read its ETag earlier still, before any body write the stamp
//     announced; the conditional PUT then loses to that write instead of
//     erasing it.
//   - The body write is conditional on the ETag it read, so any body write
//     between the two is a conflict, not a loss.
func (s *NotesService) UpdateNote(ctx context.Context, userID, noteID string, updates NoteUpdates) (model.NoteIndex, error) {
	// The body first, when there is one to write. The object key is derived
	// from the ids rather than read from the row, which is what lets the ETag
	// be read before the row is; a row naming a different key — nothing
	// writes one, but a row is data — falls back to reading after.
	//
	// The stored body is kept as well as its ETag: the client never saw the
	// worker's append markers (GetNoteDetail strips them), so they are put
	// back onto whatever it sends, or a save inside a capture's retry window
	// would erase the one fact that stops the retry appending twice.
	bodyETag := ""
	var storedBody []byte
	bodyReadFrom := ""
	if updates.Body != nil {
		key, err := keys.NoteMarkdown(userID, noteID)
		if err != nil {
			return model.NoteIndex{}, repository.ErrNotFound
		}
		storedBody, bodyETag, err = s.objects.GetWithETag(ctx, key)
		if err != nil && !errors.Is(err, repository.ErrNotFound) {
			return model.NoteIndex{}, fmt.Errorf("failed to read note body: %w", err)
		}
		bodyReadFrom = key
	}

	note, err := s.store.GetNote(ctx, userID, noteID)
	if err != nil {
		return model.NoteIndex{}, err
	}

	// Check if note is archived
	if !NoteIsActive(note) {
		return model.NoteIndex{}, ErrNoteArchived
	}

	if updates.Body != nil {
		if bodyReadFrom != note.S3MarkdownKey {
			storedBody, bodyETag, err = s.objects.GetWithETag(ctx, note.S3MarkdownKey)
			if err != nil && !errors.Is(err, repository.ErrNotFound) {
				return model.NoteIndex{}, fmt.Errorf("failed to read note body: %w", err)
			}
		}
		// Before the version check, deliberately: the stamp bumped the version,
		// so every save that meets it is also a version conflict, and answered
		// as one it would be re-read and re-sent straight into the window it
		// has to wait out.
		if AppendInProgress(note, s.now()) {
			return note, ErrAppendInProgress
		}
		// A stamp past the lease was abandoned; this write is the row's next
		// and need not carry it.
		note.AppendingCapture, note.AppendingAt = "", ""
	}

	// The version the client read is checked before anything is written, which
	// rejects the common conflict cheaply. It cannot close the window on its
	// own: an append landing after this line and before the write below is
	// caught by the ETag, not by this.
	if updates.ExpectedVersion != nil && *updates.ExpectedVersion != note.Version {
		return note, repository.ErrVersionConflict
	}

	touched, err := s.applyNoteUpdates(ctx, userID, &note, updates)
	if err != nil {
		return model.NoteIndex{}, err
	}

	if updates.Body != nil {
		if err := s.writeNoteBody(ctx, &note, storedBody, bodyETag, *updates.Body); err != nil {
			if errors.Is(err, repository.ErrVersionConflict) {
				// The row as read, for the client to reconcile against: the
				// same answer the version check above gives.
				return note, err
			}
			return model.NoteIndex{}, err
		}
	}

	// Update metadata
	if touched {
		metaData := map[string]interface{}{
			"title":      note.Title,
			"aliases":    note.Aliases,
			"tags":       note.Tags,
			"verbatim":   note.Verbatim,
			"language":   note.Language,
			"kind":       note.Kind,
			"updated_at": note.UpdatedAt,
		}
		metaBytes, _ := json.Marshal(metaData)
		err = s.objects.Put(ctx, note.S3MetaKey, metaBytes, "application/json")
		if err != nil {
			return model.NoteIndex{}, fmt.Errorf("failed to update meta: %w", err)
		}
	}

	// Save to store. A version conflict here means somebody else wrote the note
	// between the read and this write; the caller reconciles rather than one of
	// the two edits vanishing.
	return s.putCarryingStamp(ctx, userID, note)
}

// applyNoteUpdates writes each field the PATCH names onto note, validating as
// it goes, and reports whether any of them was an edit: a change to what the
// note says or is, which is what bumps updated_at and has UpdateNote rewrite
// the meta object.
//
// A pin is not an edit: it moves the note into the Pinned group, not among
// the days, so it is left out of touched. The version still moves, through
// putCarryingStamp. Before this, an unpinned note re-filed under Today and a
// pinned row read as edited just now (review 2026-09-24 R4-1).
func (s *NotesService) applyNoteUpdates(ctx context.Context, userID string, note *model.NoteIndex, updates NoteUpdates) (touched bool, err error) {
	if updates.Title != nil {
		title := sanitizeNoteTitle(*updates.Title)
		if title == "" {
			return false, ErrEmptyNoteTitle
		}
		note.Title = title
	}
	if updates.Aliases != nil {
		note.Aliases = *updates.Aliases
	}
	if updates.Tags != nil {
		note.Tags = normalizeTags(*updates.Tags)
	}
	if updates.Verbatim != nil {
		note.Verbatim = *updates.Verbatim
	}
	if updates.Language != nil {
		lang := strings.ToLower(strings.TrimSpace(*updates.Language))
		if lang != "" && !model.ValidLanguage(lang) {
			return false, ErrInvalidLanguage
		}
		note.Language = lang
	}
	if updates.AutoClean != nil {
		note.AutoClean = *updates.AutoClean
	}
	if updates.Kind != nil {
		if !model.ValidNoteKind(*updates.Kind) {
			return false, ErrInvalidNoteKind
		}
		note.Kind = *updates.Kind
	}
	if updates.CleanMode != nil {
		// Checked against the kind as this request leaves it: a note becoming
		// a checklist in this same PATCH cannot take a cleaned mode.
		if err := CheckCleanMode(*note, *updates.CleanMode); err != nil {
			return false, err
		}
		note.CleanMode = *updates.CleanMode
	}
	if updates.Pinned != nil {
		switch {
		case *updates.Pinned && !note.Pinned():
			// A new pin lands last: its rank is one step past the highest in
			// use, from the same drain that counts the pins for the limit.
			// One drain of the partition, on a pin alone.
			pinned, nextRank, err := s.countPinned(ctx, userID)
			if err != nil {
				return false, err
			}
			if pinned >= model.MaxPinnedNotes {
				return false, ErrPinLimit
			}
			note.PinnedAt = model.FormatTime(s.now())
			note.PinRank = nextRank
		case !*updates.Pinned:
			note.PinnedAt, note.PinRank = "", 0
		}
	}

	touched = updates.Title != nil || updates.Aliases != nil || updates.Tags != nil ||
		updates.Body != nil || updates.Verbatim != nil || updates.Language != nil ||
		updates.AutoClean != nil || updates.CleanMode != nil || updates.Kind != nil
	if touched {
		note.UpdatedAt = model.FormatTime(s.now())
	}
	return touched, nil
}

// writeNoteBody puts the client's draft under the ETag UpdateNote read before
// the row, with the worker's markers carried forward, and re-derives what the
// index row keeps of the body: the snippet, the search text and whether the
// cleaned view is stale.
//
// The client sends its whole draft with a Details change (language, kind,
// word-for-word, auto-clean), and a body that reads the same as the stored one
// is not an edit: CarryCaptureMarkers hands the stored bytes back for it, and
// nothing is written — a language change that marked the cleaned view stale
// had the Split up tab offer a pointless Regenerate (review 2026-09-21 r4).
//
// A body somebody else wrote between the read and this write is reported as
// repository.ErrVersionConflict: that is the same 409 the version check
// answers, and the client reconciles it the same way.
func (s *NotesService) writeNoteBody(ctx context.Context, note *model.NoteIndex, storedBody []byte, etag, body string) error {
	carried := CarryCaptureMarkers(string(storedBody), body)
	if carried == string(storedBody) {
		return nil
	}
	// Conditional on the object still carrying the ETag read above. An
	// unconditional Put here destroys a voice append that landed in the
	// meantime and only then reports the conflict — the client is told to
	// re-read text that no longer exists anywhere.
	err := s.objects.PutIfMatch(ctx, note.S3MarkdownKey, []byte(carried), "text/markdown", etag)
	if errors.Is(err, repository.ErrPreconditionFailed) {
		return repository.ErrVersionConflict
	}
	if err != nil {
		return fmt.Errorf("failed to update markdown: %w", err)
	}

	// The snippet (first ~500 chars) and the search text are the two
	// derivations of the body the index row carries.
	note.Snippet = Snippet(body)
	note.SearchText = SearchText(body)
	// The cleaned view was generated from the body that just changed — unless
	// the change was to adopt the view itself ("Use this list"): a body equal
	// to CleanedBody, trailing whitespace aside, IS the view, so it is current
	// whatever an earlier edit had marked it. Left stale, the tab offered to
	// regenerate a list identical to the note (smoke 2026-09-21, finding 3).
	trim := func(s string) string { return strings.TrimRightFunc(s, unicode.IsSpace) }
	if note.CleanedBody != "" && trim(body) == trim(note.CleanedBody) {
		note.CleanedStale = false
	} else {
		MarkCleanedStale(note)
	}
	return nil
}

// putCarryingStamp is PutNote for a write that did not touch the clean stamp.
//
// PutNote pins the stamp beside the version because a Clean tap
// (StampCleanRequest) moves the stamp without moving the version, and a
// whole-row write from a copy read before the tap would otherwise erase it. The
// pin cannot tell that stale copy from this caller, whose copy is only stale
// about the stamp: CleanedPanel fires saveNow() and regenerate() in one tick,
// so the tap routinely lands inside the save's read-modify-write window, and
// answered as a 409 the client would show a conflict prompt between two
// identical texts (the version did not move, so its rebase cannot absorb it).
// One re-read tells the two apart. The same version with a different stamp is
// the tap alone: the write goes again carrying it, and the worker finds its
// request intact. A moved version is somebody else's whole-row write, which is
// the conflict PutNote reported. On a conflict the row returned is the one now
// stored, so the handler can name the version the client has to reconcile
// against rather than 0.
func (s *NotesService) putCarryingStamp(ctx context.Context, userID string, note model.NoteIndex) (model.NoteIndex, error) {
	stored, err := s.store.PutNote(ctx, userID, note)
	if !errors.Is(err, repository.ErrVersionConflict) {
		return stored, err
	}
	fresh, readErr := s.store.GetNote(ctx, userID, note.ID)
	if readErr != nil {
		return note, err
	}
	if fresh.Version != note.Version {
		return fresh, err
	}
	note.CleanedRequestedAt, note.CleanedRequestedMode = fresh.CleanedRequestedAt, fresh.CleanedRequestedMode
	stored, err = s.store.PutNote(ctx, userID, note)
	if errors.Is(err, repository.ErrVersionConflict) {
		return fresh, err
	}
	return stored, err
}
