/**
 * HAND-WRITTEN stand-ins for responses the backend does not send yet.
 *
 * `responses.ts` beside this file is generated by the Go contract test and
 * compared byte for byte with what the router answers today, so nothing can
 * be added to it ahead of the backend. These are the shapes agreed for the
 * 2026-09-05 batch (`POST /v1/ask`, `GET /v1/ask/{id}`, the extended
 * `GET /v1/usage`), written out by hand so the screens and their tests can be
 * built against them first. The type annotations do the same job they do in
 * the generated file: a field that drifts from `schema.ts` fails typecheck.
 *
 * When the backend lands and the generator emits these, each constant here is
 * replaced by the generated one and this file goes.
 */

import type { AskWire, UsageWire } from '../schema.ts';

import { usage } from './responses.ts';

/** POST /v1/ask → 202. The row as first written: pending, nothing answered yet. */
export const askPending: AskWire = {
  answer: null,
  answered_at: null,
  created_at: '2026-01-01T00:00:00.000000000Z',
  error: null,
  grounded: false,
  id: 'fixture-ask-id',
  notes_considered: 0,
  question: 'what did I decide about the roof?',
  sources: [],
  status: 'pending',
};

/**
 * GET /v1/ask/{askId} → 200 once the worker has answered from the notes.
 * Sources are only notes the model was given AND cited, most relevant first.
 */
export const askAnswered: AskWire = {
  answer:
    'You decided to get two quotes before the rain and to have the **ridge tiles** on the south slope reset.\n\n- The tiler can start on the fourteenth.\n- The gutter leak goes to the roofer.',
  answered_at: '2026-01-01T00:00:04.000000000Z',
  created_at: '2026-01-01T00:00:00.000000000Z',
  error: null,
  grounded: true,
  id: 'fixture-ask-id',
  notes_considered: 12,
  question: 'what did I decide about the roof?',
  sources: [
    { note_id: 'fixture-note-id', title: 'Roof repair' },
    { note_id: 'fixture-note-id-2', title: 'Kitchen rebuild' },
  ],
  status: 'answered',
};

/**
 * GET /v1/ask/{askId} → 200 for a question the notes do not answer: answered,
 * not failed, with grounded false and no sources.
 */
export const askNotInNotes: AskWire = {
  answer: 'Your notes do not say anything about a car.',
  answered_at: '2026-01-01T00:00:03.000000000Z',
  created_at: '2026-01-01T00:00:00.000000000Z',
  error: null,
  grounded: false,
  id: 'fixture-ask-id',
  notes_considered: 12,
  question: 'what colour is my car?',
  sources: [],
  status: 'answered',
};

/** GET /v1/ask/{askId} → 200 after the worker gave up. `error` is one of the fixed sentences, never provider text. */
export const askFailed: AskWire = {
  answer: null,
  answered_at: '2026-01-01T00:00:30.000000000Z',
  created_at: '2026-01-01T00:00:00.000000000Z',
  error: 'the answer could not be produced; try again',
  grounded: false,
  id: 'fixture-ask-id',
  notes_considered: 12,
  question: 'what did I decide about the roof?',
  sources: [],
  status: 'failed',
};

/**
 * GET /v1/usage?month=2026-01 → 200 with the new members: the generated
 * month plus a clean-note and an ask call, the same totals split by provider,
 * the month's API requests and a per-day count of them, what is stored, and
 * the user's estimated share of the instance's AWS bill.
 *
 * Built on the generated `usage` so the two cannot drift apart on the fields
 * they share; the totals are restated because the two extra calls change them.
 */
export const usageRich: UsageWire = {
  ...usage,
  calls: 5,
  cost_micros: 2721,
  input_tokens: 5800,
  output_tokens: 850,
  ops: {
    ...usage.ops,
    clean_note: { calls: 1, cost_micros: 250, input_tokens: 700, output_tokens: 200 },
    ask: { calls: 1, cost_micros: 1100, input_tokens: 3000, output_tokens: 250 },
  },
  days: [
    {
      api_requests: 12,
      audio_seconds: 28.5,
      calls: 2,
      cost_micros: 951,
      date: '2026-01-03',
      input_tokens: 900,
      output_tokens: 300,
    },
    {
      api_requests: 9,
      calls: 3,
      cost_micros: 1770,
      date: '2026-01-04',
      input_tokens: 4900,
      output_tokens: 550,
    },
  ],
  // The keys are the generated fixture's — `openai` is the OpenAI-compatible
  // endpoint the worker meters the language model under, whatever vendor is
  // behind it — with the two extra calls added to that line.
  providers: {
    ...usage.providers,
    openai: { calls: 4, cost_micros: 2410, input_tokens: 5800, output_tokens: 850 },
  },
  api: { requests: 312 },
  storage: {
    approximate: false,
    audio_bytes: 9123456,
    audio_seconds: 1391.2,
    byte_days: 18123456,
    note_days: 23,
    notes: 12,
    recordings: 41,
  },
  aws: {
    as_of: '2026-01-05T06:00:00Z',
    budget_micros: 10000000,
    month_micros: 2345678,
    share_basis: 'provider_cost',
    share_micros: 123456,
  },
};
