#!/usr/bin/env python3
"""Generate docs/backlog-open.md, the current state of the append-only ledger docs/backlog.md.

The ledger keeps every row ever written, so "what is open" cannot be read off it:
an id's later row (a correction, a decision, a revert) is the truth and the earlier
row still reads open. This takes the LAST row per id and sorts the survivors into
four lists. It is deterministic: ages are counted from the newest dated heading in
the ledger, not from the wall clock, so CI can fail when the committed view is stale
(the same way the contract fixtures are checked) without going stale overnight.

Conventions it reads (see the legend in docs/backlog.md): a row whose Item starts
with `Correction:` / `Review of #N:` / `Superseded by <id>:` / `Reverted:` replaces
the earlier row of the same id; the Status cell may carry `gate: <what>` (a done row
that still owes a check) and `owner: <YYYY-MM-DD>` (the date the owner was asked).
"""
import datetime
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "backlog.md"
OUT = ROOT / "docs" / "backlog-open.md"
DATE = re.compile(r"\d{4}-\d{2}-\d{2}")
CLOSED = ("done", "declined", "dropped", "closed", "not reproduced", "answer")
OWNER = ("owner", "asked", "gated", "question")
# A done row owes a gate when its Status names the owner or a `gate:`, or its Notes say a
# check is owed. Bare "Pixel"/"iPhone" is not enough: most done rows cite a Pixel 7 e2e profile.
GATE_IN_STATUS = ("gate:", "owner")
GATE_IN_NOTES = re.compile(r"gate:|\*\*owner\*\*|\bowed\b|left to the owner|device check|without the live eval")
ITEM_WIDTH = 110


def parse(text):
    """Yield one dict per data row, in file order, with the nearest `##` heading and its date."""
    section, section_date = "", None
    for n, line in enumerate(text.splitlines(), 1):
        if line.startswith("## "):
            section = line[3:].strip()
            m = DATE.search(section)
            section_date = datetime.date.fromisoformat(m.group()) if m else None
            continue
        if not line.startswith("| ") or line.startswith("|---"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3 or cells[0].lower() in ("#", "id") or cells[2] == "Status":
            continue
        # `R6-RT-8 (reverted)` and `DB6-22 (correction)` are rows about R6-RT-8 and DB6-22; a
        # composite cell such as `PR-2, PR-4` is one id, and its correction row repeats it exactly.
        yield {"id": re.sub(r"\s*\(.*\)$", "", cells[0]).strip("`*"), "item": cells[1], "status": cells[2].replace("**", ""),
               "notes": " ".join(cells[3:]), "line": n, "section": section, "date": section_date}


def classify(row):
    status, notes, item = row["status"].lower(), row["notes"].lower(), row["item"].lower()
    if any(w in status for w in ("reverted", "reversed", "superseded")) or item.startswith(("reverted:", "superseded by")):
        return "reverted"
    if status.startswith(CLOSED):
        owed = any(p in status for p in GATE_IN_STATUS) or GATE_IN_NOTES.search(notes)
        return "gate" if owed else None
    return "owner" if any(w in status for w in OWNER) else "unowned"


def render(text):
    last = {}
    for row in parse(text):
        last[row["id"]] = row
    dates = [datetime.date.fromisoformat(d) for d in DATE.findall(text)]
    asof = max(dates)
    buckets = {"owner": [], "unowned": [], "gate": [], "reverted": []}
    for row in last.values():
        kind = classify(row)
        if kind == "reverted" and (row["date"] is None or (asof - row["date"]).days > 30):
            continue
        if kind:
            buckets[kind].append(row)

    def line(row):
        item = row["item"] if len(row["item"]) <= ITEM_WIDTH else row["item"][: ITEM_WIDTH - 1] + "…"
        extra = ""
        m = re.search(r"owner:\s*(\d{4}-\d{2}-\d{2})", row["status"])
        asked = datetime.date.fromisoformat(m.group(1)) if m else row["date"]
        if row in buckets["owner"]:
            extra = f" · asked {asked} ({(asof - asked).days} d)" if asked else " · asked (undated)"
        m = re.search(r"gate:\s*([^;|]+)", row["status"])
        if m:
            extra += f" · gate: {m.group(1).strip()}"
        return f"- {row['id']} · {row['section']} · L{row['line']}{extra} · {item}"

    counts = {k: len(v) for k, v in buckets.items()}
    out = [
        "# Backlog — open items",
        "",
        f"Generated by `scripts/backlog-view.py` from `docs/backlog.md`; do not edit. Last row per id wins. "
        f"Ages are as of {asof}, the newest dated heading in the ledger. "
        f"Counts: owner {counts['owner']} · unowned {counts['unowned']} · gate owed {counts['gate']} · reverted {counts['reverted']}.",
        "",
        "## Needs the owner", "",
        *[line(r) for r in buckets["owner"]], "",
        "## Open, unowned", "",
        *[line(r) for r in buckets["unowned"]], "",
        "## Done, gate owed", "",
        *[line(r) for r in buckets["gate"]], "",
        "## Reverted / superseded (30 days)", "",
        *[line(r) for r in buckets["reverted"]], "",
    ]
    return "\n".join(out), counts


def self_test():
    """The smallest ledger that exercises every rule; fails loudly if a rule breaks."""
    ledger = """## Round 1 — 2026-09-05
| # | Item | Status | Notes |
|---|---|---|---|
| A1 | first | **queued** (owner) | |
| A2 | second | **done** | iPhone check still owed. |
| A3 | third | **done** (frontend) | shipped on a Pixel 7 profile; the swallowed click |
| A4 | fourth | next | |
| A5 | Reverted: fifth | **done** | |
## Round 2 — 2026-10-02
| Id | Finding | Status | What changed |
|---|---|---|---|
| A1 | Correction: decided | **done** | |
| A4 (follow-up) | still open | open (owner: 2026-09-20) | |
"""
    text, counts = render(ledger)
    assert counts == {"owner": 1, "unowned": 0, "gate": 1, "reverted": 1}, counts
    assert "A4 · Round 2 — 2026-10-02 · L13 · asked 2026-09-20 (12 d)" in text, text
    assert "- A2 · Round 1" in text and "A3" not in text and "A1" not in text, text
    assert render(ledger.replace("2026-09-05", "2026-08-01"))[1]["reverted"] == 0  # A5 falls out of the 30-day window


if __name__ == "__main__":
    import sys

    if sys.argv[1:] == ["--self-test"]:
        self_test()
        sys.exit(print("self-test ok"))
    text, counts = render(SRC.read_text())
    OUT.write_text(text)
    print(f"{OUT.relative_to(ROOT)}: " + " · ".join(f"{k} {v}" for k, v in counts.items()))
